### ISSUE TITLE
Error in installation setup.log

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#10]
To see basic server configuration status and configuration you can launch /opt/opendj/bin/status

08:07:00 01/22/15 Unable to initialize log
java.io.IOException: Permission denied
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at java.io.File.createTempFile(File.java:1989)
	at java.io.File.createTempFile(File.java:2040)
	at org.opends.quicksetup.installer.SetupLauncher.main(SetupLauncher.java:68)
Unable to initialize log
java.io.IOException: Permission denied
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at java.io.File.createTempFile(File.java:1989)
	at java.io.File.createTempFile(File.java:2040)
	at org.opends.server.tools.InstallDS.mainCLI(InstallDS.java:331)
	at org.opends.server.tools.InstallDS.mainCLI(InstallDS.java:286)
	at org.opends.quicksetup.installer.SetupLauncher.launch(SetupLauncher.java:138)
	at org.opends.quicksetup.installer.SetupLauncher.main(SetupLauncher.java:75)
Jan 22, 2015 8:06:32 AM org.opends.quicksetup.CurrentInstallStatus getPort
INFO: Failed to get port
java.io.FileNotFoundException: /opt/opendj/./config/config.ldif (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at java.io.FileReader.<init>(FileReader.java:72)
	at org.opends.quicksetup.Configuration.load(Configuration.java:331)
	at org.opends.quicksetup.Configuration.getLowerCaseContents(Configuration.java:298)
	at org.opends.quicksetup.Configuration.getLDAPPort(Configuration.java:191)
	at org.opends.quicksetup.Configuration.getPort(Configuration.java:92)
	at org.opends.quicksetup.CurrentInstallStatus.getPort(CurrentInstallStatus.java:178)
	at org.opends.quicksetup.CurrentInstallStatus.<init>(CurrentInstallStatus.java:80)
	at org.opends.server.tools.InstallDS.checkInstallStatus(InstallDS.java:622)
	at org.opends.server.tools.InstallDS.execute(InstallDS.java:417)
	at org.opends.server.tools.InstallDS.mainCLI(InstallDS.java:341)
	at org.opends.server.tools.InstallDS.mainCLI(InstallDS.java:286)
	at org.opends.quicksetup.installer.SetupLauncher.launch(SetupLauncher.java:138)
	at org.opends.quicksetup.installer.SetupLauncher.main(SetupLauncher.java:75)

Failed to initialize log
Jan 22, 2015 8:06:32 AM org.opends.quicksetup.util.FileManager$CopyOperation apply

**Comment by yurem** [comment]
https://bugster.forgerock.org/jira/browse/OPENAM-4466

Hence it's not installation issue
