### ISSUE TITLE
fix: MySQL indexes are not created on SUSE15

### ISSUE THREAD

**Issue by devrimyatar** [GluuFederation/community-edition-setup#1020]
```
07:13:52 12/01/23 ERROR executing query ('(pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that correspo
07:13:52 12/01/23 Traceback (most recent call last):
  File "/install/community-edition-setup/setup_app/pylib/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/install/community-edition-setup/setup_app/pylib/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python3.6/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/lib/python3.6/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/lib/python3.6/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib/python3.6/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/lib/python3.6/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/lib/python3.6/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/lib/python3.6/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python3.6/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
```

**Comment by devrimyatar** [comment]
Also check
```
17:27:15 12/01/23 Executing mysql Query: ALTER TABLE gluudb.cache ADD INDEX `cache_CustomIdx1` (`del`, `exp`);
17:27:15 12/01/23 Executing mysql Query: ALTER TABLE gluudb.cibaRequest ADD INDEX `clnId_json_1`((CAST(clnId->'$.v' AS CHAR(128) ARRAY)));
17:27:15 12/01/23 ERROR executing query ('(pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your
17:27:15 12/01/23 Executing mysql Query: ALTER TABLE gluudb.cibaRequest ADD INDEX `clnId_json_2`((CAST(clnId->'$.v[0]' AS CHAR(128))));
17:27:15 12/01/23 ERROR executing query ('(pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your
17:27:15 12/01/23 Executing mysql Query: ALTER TABLE gluudb.cibaRequest ADD INDEX `clnId_json_3`((CAST(clnId->'$.v[1]' AS CHAR(128))));
17:27:15 12/01/23 ERROR executing query ('(pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your
17:27:15 12/01/23 Executing mysql Query: ALTER TABLE gluudb.cibaRequest ADD INDEX `clnId_json_4`((CAST(clnId->'$.v[2]' AS CHAR(128))));
17:27:15 12/01/23 ERROR executing query ('(pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your
```
