### ISSUE TITLE
RHEL 6.7. Failed to creat log during opendj setup

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#116]
In setup.log there is error:

06:36:08 04/20/16 Unable to initialize log
java.io.IOException: Permission denied
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2001)
	at java.io.File.createTempFile(File.java:2047)
	at org.opends.quicksetup.installer.SetupLauncher.main(SetupLauncher.java:58)
Unable to initialize log
java.io.IOException: Permission denied
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2001)
	at java.io.File.createTempFile(File.java:2047)
	at org.opends.server.tools.InstallDS.mainCLI(InstallDS.java:296)
	at org.opends.server.tools.InstallDS.mainCLI(InstallDS.java:268)
	at org.opends.quicksetup.installer.SetupLauncher.launch(SetupLauncher.java:118)
	at org.opends.quicksetup.installer.SetupLauncher.main(SetupLauncher.java:65)
Apr 20, 2016 6:35:55 AM org.forgerock.i18n.slf4j.LocalizedLogger info
INFO: Failed to get port

But CE works fine after install

**Comment by yurem** [comment]
Here is the problem
GLUU.[root@localhost community-edition-setup]# ls -l / | grep tmp
drwxr-xr-t.   4 root root  4096 Apr 20 06:35 tmp

**Comment by yurem** [comment]
But right /tmp folder permission should be:
drwxrwxrwt.  15 root root  4096 Apr 20 04:01 tmp

**Comment by adrian-gluu** [comment]
fixed again http://repo.gluu.org/centos/testing/gluu-server-2.4.3-1-2.centos6.x86_64.rpm
