### ISSUE TITLE
check_ssl error in CentOS 6.7 CE

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#154]
GLUU.[root@localhost logs]# su - tomcat
[tomcat@localhost ~]$ check_ssl
unable to load certificate
140580307769160:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:703:Expecting: TRUSTED CERTIFICATE
Traceback (most recent call last):
  File "/usr/local/bin/check_ssl.py", line 13, in <module>
    time_tup = time.strptime(t, '%b %d %H:%M:%S %Y %Z')
  File "/usr/lib64/python2.6/_strptime.py", line 454, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib64/python2.6/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%b %d %H:%M:%S %Y %Z'

**Comment by yurem** [comment]
@uboznikov 
There is this issue in CentOS/RHEL 6.7/7/0
I can reproduce it after VM suspend/resume. Once I did that hostname in VM becomes invalid.

I offer to ignore it because in real scenario customer can't suspend their server.
