### ISSUE TITLE
Gluu Server does not SSL connection for localhost (prevents oxd from working on the same machine where Gluu Server installed)

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/community-edition-setup#157]
Bug described by this support ticket:
`https://support.gluu.org/integrations/ssl-exception-oxd-client-243-final-gluu-server-2-4-3-2975`

If connect to Gluu Server endpoints (for example https://ce-dev.gluu.org/.well-known/openid-configuration ) from outside it is returned as https. However if connect to it from the same machine it is not encrypted and its returned as plain connection (unencrypted). Is it problem in apache configuration?

This issue leads to problem when customer installs oxD Server on the same machine as Gluu Server. oxD can not verify connection due to error below (plain connection instead of https).

```
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
    at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710)
    at sun.security.ssl.InputRecord.read(InputRecord.java:527)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
    at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:747)
    at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
    at org.apache.http.impl.io.AbstractSessionOutputBuffer.flushBuffer(AbstractSessionOutputBuffer.java:159)
    at org.apache.http.impl.io.AbstractSessionOutputBuffer.flush(AbstractSessionOutputBuffer.java:166)
    at org.apache.http.impl.AbstractHttpClientConnection.doFlush(AbstractHttpClientConnection.java:272)
    at org.apache.http.impl.AbstractHttpClientConnection.flush(AbstractHttpClientConnection.java:277)
    at org.apache.http.impl.conn.ManagedClientConnectionImpl.flush(ManagedClientConnectionImpl.java:175)
    at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:239)
    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
    at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:717)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:522)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
    at org.jboss.resteasy.client.core.executors.ApacheHttpClient4Executor.execute(ApacheHttpClient4Executor.java:109)
    at org.jboss.resteasy.core.interception.ClientExecutionContextImpl.proceed(ClientExecutionContextImpl.java:39)
    at org.jboss.resteasy.plugins.interceptors.encoding.AcceptEncodingGZIPInterceptor.execute(AcceptEncodingGZIPInterceptor.java:40)
    at org.jboss.resteasy.core.interception.ClientExecutionContextImpl.proceed(ClientExecutionContextImpl.java:45)
    at org.jboss.resteasy.client.ClientRequest.execute(ClientRequest.java:443)
    at org.jboss.resteasy.client.ClientRequest.httpMethod(ClientRequest.java:677)
    at org.jboss.resteasy.client.ClientRequest.get(ClientRequest.java:479)
    at org.jboss.resteasy.client.ClientRequest.get(ClientRequest.java:508)
    at org.xdi.oxauth.client.OpenIdConfigurationClient._execOpenIdConfiguration(OpenIdConfigurationClient.java:102)
    at org.xdi.oxauth.client.OpenIdConfigurationClient.execOpenIdConfiguration(OpenIdConfigurationClient.java:78)
    at org.xdi.oxd.server.service.DiscoveryService.getConnectDiscoveryResponse(DiscoveryService.java:60)
    at org.xdi.oxd.server.op.ImplicitFlowOperation.execute(ImplicitFlowOperation.java:42)
```

**Comment by yurem** [comment]
Why we need to issue certs for localhost?
In CE 3.0.0 all applications we run on http port under jetty. And we uses apache http proxy to protect them by SSL.

**Comment by yurem** [comment]
According to setup we import all generated certs in default java trustore. Hence default configuration should works fine.
But I suspect in your case we changed self signed apache cert with real cert. In this case admin should manually import new cert into default java truststore
