### ISSUE TITLE
Add Certificate to keystore exception (Asimba's keystore)

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/community-edition-setup#163]
2.4.4, Ubuntu 16.04

INFO   | jvm 1    | 2016/08/04 18:22:26 | 2016-08-04 18:22:26,619 INFO  [org.gluu.oxtrust.service.asimba.AsimbaXMLConfigurationService] AsimbaXMLConfig keystoreFilePath: /etc/certs/asimbaIDP.jks
INFO   | jvm 1    | 2016/08/04 18:22:26 | 2016-08-04 18:22:26,621 INFO  [org.gluu.oxtrust.service.asimba.AsimbaXMLConfigurationService] AsimbaXMLConfig keystoreType: JKS
INFO   | jvm 1    | 2016/08/04 18:22:26 | 2016-08-04 18:22:26,627 ERROR [org.gluu.oxtrust.service.asimba.AsimbaXMLConfigurationService] Add Certificate to keystore exception
INFO   | jvm 1    | 2016/08/04 18:22:26 | java.io.FileNotFoundException: /etc/certs/asimbaIDP.jks (Permission denied)
INFO   | jvm 1    | 2016/08/04 18:22:26 |       at java.io.FileOutputStream.open0(Native Method)
INFO   | jvm 1    | 2016/08/04 18:22:26 |       at java.io.FileOutputStream.open(FileOutputStream.java:270)
INFO   | jvm 1    | 2016/08/04 18:22:26 |       at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
INFO   | jvm 1    | 2016/08/04 18:22:26 |       at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
INFO   | jvm 1    | 2016/08/04 18:22:26 |       at org.gluu.oxtrust.util.KeystoreWrapper.save(KeystoreWrapper.java:65)
INFO   | jvm 1    | 2016/08/04 18:22:26 |       at org.gluu.oxtrust.service.asimba.AsimbaXMLConfigurationService.addCertificateFile(AsimbaXMLConfigurationService.java:169)

- add write permission for tomcat user in the installer.

**Comment by dmogn** [comment]
Fixed.

https://github.com/GluuFederation/community-edition-setup/commit/a145261f7f47d98a19ef7dd9b1ddb1ff34c8345f#diff-2eeaed663bd0d25b7e608891384b7298
