### ISSUE TITLE
Fix OS detection method

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#21]
There is problem with our scripts on Ubuntu
[18:37:54] Yuriy Movchan: Enter IP Address [192.168.74.150] :
Enter hostname [ce.gluu.info] : u14.gluu.info
Traceback (most recent call last):
  File "./setup.py", line 1429, in <module>
    installObject.promptForProperties()
  File "./setup.py", line 1073, in promptForProperties
    installObject.os_type = installObject.detect_OS_type()
  File "./setup.py", line 503, in detect_OS_type
    distro_info = self.file_get_contents('/etc/redhat-release')
  File "./setup.py", line 577, in file_get_contents
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: '/etc/redhat-release'

**Comment by yurem** [comment]
GLUU.root@ce:/install/community-edition-setup# find /etc -name *release
/etc/lsb-release

**Comment by yurem** [comment]
GLUU.root@ce:/install/community-edition-setup# cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.1 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.1 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
