### ISSUE TITLE
CentOS 6.6 Package gluu-server-3.0.0.x86_64 1-BETA4.centos6 errors

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/community-edition-setup#260]
Package installation work fine, but nothing works. The `setup_error.log` contains the following

```
GLUU.[root@localhost community-edition-setup]# cat setup_error.log 
22:23:41 01/23/17 Installing Gluu Server
22:28:46 01/23/17 2017-01-23 22:28:46 URL:https://ox.gluu.org/maven/org/xdi/oxauth-rp/3.0.0-SNAPSHOT/oxauth-rp-3.0.0-SNAPSHOT.war [32660185/32660185] -> "/opt/dist/gluu/oxauth-rp.war" [1]

22:28:55 01/23/17 ***** Error caught in main loop *****
22:28:55 01/23/17 Traceback (most recent call last):
  File "./setup.py", line 2632, in <module>
    installObject.installJetty()
  File "./setup.py", line 993, in installJetty
    self.applyChangesInFiles(self.app_custom_changes['jetty'])
  File "./setup.py", line 688, in applyChangesInFiles
    text = self.replaceInText(text, replace['pattern'], replace['update'])
  File "./setup.py", line 675, in replaceInText
    return re.sub(pattern, update, text, flags=re.DOTALL | re.M)
TypeError: sub() got an unexpected keyword argument 'flags'
```
No service is started
```
GLUU.[root@localhost community-edition-setup]# service httpd status
httpd (pid  16477) is running...
GLUU.[root@localhost community-edition-setup]# service oxauth status
oxauth: unrecognized service
GLUU.[root@localhost community-edition-setup]# service identity status
identity: unrecognized service
```
ASIMBA was not installed
```
Install oxAuth                                               True
Install oxTrust                                              True
Install LDAP                                                 True
Install Apache 2 web server                                  True
Install Shibboleth SAML IDP                                  True
Install Asimba SAML Proxy                                   False
Install CAS                                                 False
Install oxAuth RP                                            True
Install Passport                                             True
```

**Comment by yurem** [comment]
I added workaround to allow run this on old Python 2.6.6: https://github.com/GluuFederation/community-edition-setup/commit/0d3e0d9c7362de147d71171afa4c296440dd83ff

Fixed and tested
