### ISSUE TITLE
Upgrade: 2.4.4 export script not working

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#363]
export script from 2.4.4 is not working: 

```
GLUU.root@localhost:~# ./export2431.py
./export2431.py: line 1: #!/usr/bin/env: No such file or directory
./export2431.py: line 19: backup_2431: command not found
./export2431.py: line 19: import___.py: command not found
./export2431.py: line 19: export2431.py - A script to export all the data from Gluu Server 2.4.x

Usage: python export2431.py

Running this creates a folder named  which contains all the data
needed for migration of Gluu Server to a higher version. This script backs up
the following data:
    1. LDAP data
    2. Configurations of Tomcat and OpenDJ
    3. CA certificates in /etc/certs
    4. Webapp Customization files

This backup folder should be used as the input for the  script
of appropriate version to migrate to that version.

Read complete migration procedure at:
    https://www.gluu.org/docs/deployment/upgrading/
: File name too long
./export2431.py: line 20: import: command not found
./export2431.py: line 21: import: command not found
./export2431.py: line 22: import: command not found
./export2431.py: line 23: import: command not found
./export2431.py: line 24: import: command not found
./export2431.py: line 25: import: command not found
./export2431.py: line 26: import: command not found
./export2431.py: line 27: import: command not found
./export2431.py: line 28: import: command not found
./export2431.py: line 29: import: command not found
./export2431.py: line 30: import: command not found
from: can't read /var/mail/ldif
from: can't read /var/mail/distutils.dir_util
./export2431.py: line 33: import: command not found
from: can't read /var/mail/shutil
./export2431.py: line 35: import: command not found
./export2431.py: line 38: syntax error near unexpected token `('
./export2431.py: line 38: `class MyLDIF(LDIFParser):'

```

**Comment by sahiliamsso** [comment]
It works fine with this command "python export2431.py" on ubunty14.04

GLUU.root@ubuntu2:~# python export2431.py
-------------------------------------------------------------
            Gluu Server Data Export Tool For v2.4x to v3.1x           
-------------------------------------------------------------

INFO     Creating backup of files
INFO     Creating backup of LDAP data
INFO     Creating setup.properties backup file
 Is Shibboleth SAML IDP installed? (y/N): [N]y
 Install passport in new version? (y/N): [N]y

-------------------------------------------------------------
The data has been exported to backup_2431
-------------------------------------------------------------

**Comment by mzico** [comment]
@sahiliamsso : failing for me [ ignore idp related warning ]: 

```
GLUU.root@localhost:~# python export2431.py
-------------------------------------------------------------
            Gluu Server Data Export Tool For v2.4x to v3.1x
-------------------------------------------------------------

INFO     Creating backup of files
ERROR    Failed to backup /opt/idp/conf
ERROR    Failed to backup /opt/idp/metadata
INFO     Creating backup of LDAP data
Traceback (most recent call last):
  File "export2431.py", line 618, in <module>
    exporter.export()
  File "export2431.py", line 605, in export
    self.getLdif()
  File "export2431.py", line 474, in getLdif
    doUmaResourcesChangesForUma2(self, "%s/ldif/uma.ldif" % self.backupDir)
  File "export2431.py", line 310, in doUmaResourcesChangesForUma2
    parser.getDNs()[idx] = parser.getDNs()[idx].replace('inum=' + val['inum'][0],
KeyError: 'inum'
GLUU.root@localhost:~#
```

**Comment by mzico** [comment]
3.1.1 and 3.1.2 has UMA 2.0. Previous versions has UMA 1.0. 
We need to figure out how to upgrade from UMA 1.0 to UMA 2.0 after 3.1.2

**Comment by willow9886** [comment]
> We need to figure out how to upgrade from UMA 1.0 to UMA 2.0 after 3.1.2 

There are breaking changes... so I think it's up to the user/org to update all their UMA clients. I don't think we can offer a quick or easy upgrade path. Needs to be evaluated on a client by client basis.
