### ISSUE TITLE
3.0.2 --> 3.1.2 upgrade / admin users rejected by Cache Refresh in 3.1.2

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#422]
After 3.0.2 --> 3.1.2 upgrade, I ran Cache Refresh from 3.1.2 to sync user information but for below reason ( stack trace from cache_refresh.log ), 4 users are removed and not populating in 3.1.2. These four users were in GluuManager group ( screenshot: upper section from group.ldif exported data; lower one is in 3.1.2  ). I am exactly not sure if it some issue with OpenLDAP but I don't have facility to check OpenLDAP --> OpenDJ upgrade at this moment. 

```
2018-04-20 11:10:01,920 ERROR [ForkJoinPool.commonPool-worker-1] [gluu.oxtrust.ldap.cache.service.CacheRefreshTimer] (CacheRefreshTimer.java:684) - Failed to 'add' person '@!6D63.C883.EAA6.2532!0001!7130.DF64!0000!6769.9726'
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to persist entry: inum=@!6D63.C883.EAA6.2532!0001!7130.DF64!0000!6769.9726,ou=people,o=@!6D63.C883.EAA6.2532!0001!7130.DF64,o=gluu
	at org.gluu.site.ldap.persistence.LdapEntryManager.persist(LdapEntryManager.java:124) ~[oxcore-ldap-3.1.2.Final.jar:?]
	at org.gluu.site.ldap.persistence.AbstractEntryManager.persist(AbstractEntryManager.java:90) ~[oxcore-ldap-3.1.2.Final.jar:?]
	at org.gluu.site.ldap.persistence.LdapEntryManager$Proxy$_$$_WeldClientProxy.persist(Unknown Source) ~[oxcore-ldap-3.1.2.Final.jar:?]
	at org.gluu.oxtrust.ldap.service.PersonService.addPerson(PersonService.java:103) ~[classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.updateTargetEntryViaCopy(CacheRefreshTimer.java:680) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.updateTargetEntriesViaCopy(CacheRefreshTimer.java:569) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.detectChangedEntries(CacheRefreshTimer.java:392) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.processImpl(CacheRefreshTimer.java:283) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.processInt(CacheRefreshTimer.java:194) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer$Proxy$_$$_WeldSubclass.processInt(Unknown Source) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.process(CacheRefreshTimer.java:177) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer$Proxy$_$$_WeldSubclass.process$$super(Unknown Source) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor564.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
	at org.xdi.service.cdi.async.AsynchronousInterceptor$1.get(AsynchronousInterceptor.java:36) [oxcore-service-3.1.2.Final.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_112]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) [?:1.8.0_112]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_112]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_112]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_112]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_112]
Caused by: com.unboundid.ldap.sdk.LDAPException: no such object
	at com.unboundid.ldap.sdk.LDAPConnection.add(LDAPConnection.java:1959) ~[unboundid-ldapsdk-3.2.0.jar:3.2.0]
	at com.unboundid.ldap.sdk.AbstractConnectionPool.add(AbstractConnectionPool.java:752) ~[unboundid-ldapsdk-3.2.0.jar:3.2.0]
	at com.unboundid.ldap.sdk.AbstractConnectionPool.add(AbstractConnectionPool.java:683) ~[unboundid-ldapsdk-3.2.0.jar:3.2.0]
	at org.gluu.site.ldap.OperationsFacade.addEntry(OperationsFacade.java:533) ~[oxcore-ldap-3.1.2.Final.jar:?]
	at org.gluu.site.ldap.persistence.LdapEntryManager.persist(LdapEntryManager.java:119) ~[oxcore-ldap-3.1.2.Final.jar:?]
	... 23 more
2018-04-20 11:10:04,457 ERROR [ForkJoinPool.commonPool-worker-1] [gluu.oxtrust.ldap.cache.service.CacheRefreshTimer] (CacheRefreshTimer.java:684) - Failed to 'add' person '@!6D63.C883.EAA6.2532!0001!7130.DF64!0000!569B.8992'
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to persist entry: inum=@!6D63.C883.EAA6.2532!0001!7130.DF64!0000!569B.8992,ou=people,o=@!6D63.C883.EAA6.2532!0001!7130.DF64,o=gluu
	at org.gluu.site.ldap.persistence.LdapEntryManager.persist(LdapEntryManager.java:124) ~[oxcore-ldap-3.1.2.Final.jar:?]
	at org.gluu.site.ldap.persistence.AbstractEntryManager.persist(AbstractEntryManager.java:90) ~[oxcore-ldap-3.1.2.Final.jar:?]
	at org.gluu.site.ldap.persistence.LdapEntryManager$Proxy$_$$_WeldClientProxy.persist(Unknown Source) ~[oxcore-ldap-3.1.2.Final.jar:?]
	at org.gluu.oxtrust.ldap.service.PersonService.addPerson(PersonService.java:103) ~[classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.updateTargetEntryViaCopy(CacheRefreshTimer.java:680) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.updateTargetEntriesViaCopy(CacheRefreshTimer.java:569) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.detectChangedEntries(CacheRefreshTimer.java:392) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.processImpl(CacheRefreshTimer.java:283) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.processInt(CacheRefreshTimer.java:194) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer$Proxy$_$$_WeldSubclass.processInt(Unknown Source) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.process(CacheRefreshTimer.java:177) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer$Proxy$_$$_WeldSubclass.process$$super(Unknown Source) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor564.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
	at org.xdi.service.cdi.async.AsynchronousInterceptor$1.get(AsynchronousInterceptor.java:36) [oxcore-service-3.1.2.Final.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_112]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) [?:1.8.0_112]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_112]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_112]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_112]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_112]
Caused by: com.unboundid.ldap.sdk.LDAPException: no such object
	at com.unboundid.ldap.sdk.LDAPConnection.add(LDAPConnection.java:1959) ~[unboundid-ldapsdk-3.2.0.jar:3.2.0]
	at com.unboundid.ldap.sdk.AbstractConnectionPool.add(AbstractConnectionPool.java:752) ~[unboundid-ldapsdk-3.2.0.jar:3.2.0]
	at com.unboundid.ldap.sdk.AbstractConnectionPool.add(AbstractConnectionPool.java:683) ~[unboundid-ldapsdk-3.2.0.jar:3.2.0]
	at org.gluu.site.ldap.OperationsFacade.addEntry(OperationsFacade.java:533) ~[oxcore-ldap-3.1.2.Final.jar:?]
	at org.gluu.site.ldap.persistence.LdapEntryManager.persist(LdapEntryManager.java:119) ~[oxcore-ldap-3.1.2.Final.jar:?]
	... 23 more
2018-04-20 11:10:16,155 ERROR [ForkJoinPool.commonPool-worker-1] [gluu.oxtrust.ldap.cache.service.CacheRefreshTimer] (CacheRefreshTimer.java:684) - Failed to 'update' person '@!6D63.C883.EAA6.2532!0001!7130.DF64!0000!9C03.9B91'
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to update entry: inum=@!6D63.C883.EAA6.2532!0001!7130.DF64!0000!9C03.9B91,ou=people,o=@!6D63.C883.EAA6.2532!0001!7130.DF64,o=gluu
	at org.gluu.site.ldap.persistence.LdapEntryManager.merge(LdapEntryManager.java:227) ~[oxcore-ldap-3.1.2.Final.jar:?]
	at org.gluu.site.ldap.persistence.AbstractEntryManager.merge(AbstractEntryManager.java:277) ~[oxcore-ldap-3.1.2.Final.jar:?]
	at org.gluu.site.ldap.persistence.AbstractEntryManager.merge(AbstractEntryManager.java:298) ~[oxcore-ldap-3.1.2.Final.jar:?]
	at org.gluu.site.ldap.persistence.LdapEntryManager$Proxy$_$$_WeldClientProxy.merge(Unknown Source) ~[oxcore-ldap-3.1.2.Final.jar:?]
	at org.gluu.oxtrust.ldap.service.PersonService.updatePerson(PersonService.java:115) ~[classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.updateTargetEntryViaCopy(CacheRefreshTimer.java:677) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.updateTargetEntriesViaCopy(CacheRefreshTimer.java:569) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.detectChangedEntries(CacheRefreshTimer.java:392) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.processImpl(CacheRefreshTimer.java:283) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.processInt(CacheRefreshTimer.java:194) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer$Proxy$_$$_WeldSubclass.processInt(Unknown Source) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.process(CacheRefreshTimer.java:177) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer$Proxy$_$$_WeldSubclass.process$$super(Unknown Source) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor564.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
	at org.xdi.service.cdi.async.AsynchronousInterceptor$1.get(AsynchronousInterceptor.java:36) [oxcore-service-3.1.2.Final.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_112]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) [?:1.8.0_112]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_112]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_112]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_112]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_112]
Caused by: com.unboundid.ldap.sdk.LDAPException: memberOf;range=0-1499: AttributeDescription contains inappropriate characters
	at com.unboundid.ldap.sdk.LDAPConnection.modify(LDAPConnection.java:2754) ~[unboundid-ldapsdk-3.2.0.jar:3.2.0]
	at com.unboundid.ldap.sdk.AbstractConnectionPool.modify(AbstractConnectionPool.java:1304) ~[unboundid-ldapsdk-3.2.0.jar:3.2.0]
	at org.gluu.site.ldap.OperationsFacade.modifyEntry(OperationsFacade.java:602) ~[oxcore-ldap-3.1.2.Final.jar:?]
	at org.gluu.site.ldap.OperationsFacade.updateEntry(OperationsFacade.java:588) ~[oxcore-ldap-3.1.2.Final.jar:?]
	at org.gluu.site.ldap.persistence.LdapEntryManager.merge(LdapEntryManager.java:221) ~[oxcore-ldap-3.1.2.Final.jar:?]
	... 24 more


2018-04-20 11:10:38,367 ERROR [ForkJoinPool.commonPool-worker-1] [gluu.oxtrust.ldap.cache.service.CacheRefreshTimer] (CacheRefreshTimer.java:684) - Failed to 'add' person '@!6D63.C883.EAA6.2532!0001!7130.DF64!0000!C3A2.22D9'
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to persist entry: inum=@!6D63.C883.EAA6.2532!0001!7130.DF64!0000!C3A2.22D9,ou=people,o=@!6D63.C883.EAA6.2532!0001!7130.DF64,o=gluu
	at org.gluu.site.ldap.persistence.LdapEntryManager.persist(LdapEntryManager.java:124) ~[oxcore-ldap-3.1.2.Final.jar:?]
	at org.gluu.site.ldap.persistence.AbstractEntryManager.persist(AbstractEntryManager.java:90) ~[oxcore-ldap-3.1.2.Final.jar:?]
	at org.gluu.site.ldap.persistence.LdapEntryManager$Proxy$_$$_WeldClientProxy.persist(Unknown Source) ~[oxcore-ldap-3.1.2.Final.jar:?]
	at org.gluu.oxtrust.ldap.service.PersonService.addPerson(PersonService.java:103) ~[classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.updateTargetEntryViaCopy(CacheRefreshTimer.java:680) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.updateTargetEntriesViaCopy(CacheRefreshTimer.java:569) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.detectChangedEntries(CacheRefreshTimer.java:392) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.processImpl(CacheRefreshTimer.java:283) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.processInt(CacheRefreshTimer.java:194) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer$Proxy$_$$_WeldSubclass.processInt(Unknown Source) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.process(CacheRefreshTimer.java:177) [classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer$Proxy$_$$_WeldSubclass.process$$super(Unknown Source) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor564.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
	at org.xdi.service.cdi.async.AsynchronousInterceptor$1.get(AsynchronousInterceptor.java:36) [oxcore-service-3.1.2.Final.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_112]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) [?:1.8.0_112]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_112]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_112]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_112]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_112]
Caused by: com.unboundid.ldap.sdk.LDAPException: no such object
	at com.unboundid.ldap.sdk.LDAPConnection.add(LDAPConnection.java:1959) ~[unboundid-ldapsdk-3.2.0.jar:3.2.0]
	at com.unboundid.ldap.sdk.AbstractConnectionPool.add(AbstractConnectionPool.java:752) ~[unboundid-ldapsdk-3.2.0.jar:3.2.0]
	at com.unboundid.ldap.sdk.AbstractConnectionPool.add(AbstractConnectionPool.java:683) ~[unboundid-ldapsdk-3.2.0.jar:3.2.0]
	at org.gluu.site.ldap.OperationsFacade.addEntry(OperationsFacade.java:533) ~[oxcore-ldap-3.1.2.Final.jar:?]
	at org.gluu.site.ldap.persistence.LdapEntryManager.persist(LdapEntryManager.java:119) ~[oxcore-ldap-3.1.2.Final.jar:?]
	... 23 more
2018-04-20 11:10:56,518 INFO  [ForkJoinPool.commonPool-worker-1] [gluu.oxtrust.ldap.cache.service.CacheRefreshTimer] (CacheRefreshTimer.java:395) - Updated '101212' entries
2018-04-20 11:10:56,531 INFO  [ForkJoinPool.commonPool-worker-1] [gluu.oxtrust.ldap.cache.service.CacheRefreshTimer] (CacheRefreshTimer.java:397) - Failed to update '4' entries
```

![problemadmingroup](https://user-images.githubusercontent.com/7156097/39062496-5ad7ca42-448d-11e8-8df9-6499e14ee45b.png)

**Comment by mzico** [comment]
@mbaser : Seems like it's OpenLDAP related issue. I just tried to upgrade in 'Gluu-compiled-OpenDJ' enabled 3.1.2. No issue like  above.

**Comment by mbaser** [comment]
Tested three times and could not replicate this. Closed up to one replicates.
