### ISSUE TITLE
3.1.2 --> 3.1.3 upgrade: identity throwing jar missing issue

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#429]
I tried to followed this ( https://gluu.org/docs/ce/3.1.3/upgrade/#upgrade-from-31x-to-313 ) doc to perform an upgrade from 3.1.2 ( OpenDJ ) to 3.1.3 ( OpenDJ ); but identity failed to process. Also 'oxtrust.log' were missing. 
I also remove 'identity' and 'oxauth' related directories from '/opt/jetty-9.3/temp/' location but didn't help. 

Here is the error from 'stderrout.log': 

```
2018-05-03 20:20:00.380:INFO:oejs.Server:main: jetty-9.3.15.v20161220
2018-05-03 20:20:00.424:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///opt/gluu/jetty/identity/webapps/] at interval 1
2018-05-03 20:20:09.597:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=8163ms
2018-05-03 20:20:09.598:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@13deb50e{/identity,[file:///opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1319925543506767746.dir/webapp/, jar:file:///opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1319925543506767746.dir/webapp/WEB-INF/lib/oxtrust-static-3.1.3.Final.jar!/META-INF/resources, jar:file:///opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1319925543506767746.dir/webapp/WEB-INF/lib/jsf-impl-2.2.17.jar!/META-INF/resources, jar:file:///opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1319925543506767746.dir/webapp/WEB-INF/lib/richfaces-4.5.17.Final.jar!/META-INF/resources, jar:file:///opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1319925543506767746.dir/webapp/WEB-INF/lib/richfaces-core-4.5.17.Final.jar!/META-INF/resources, jar:file:///opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1319925543506767746.dir/webapp/WEB-INF/lib/omnifaces-2.6.6.jar!/META-INF/resources, jar:file:///opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1319925543506767746.dir/webapp/WEB-INF/lib/richfaces-a4j-4.5.17.Final.jar!/META-INF/resources],UNAVAILABLE}{/identity.war}
MultiException[java.lang.RuntimeException: Error scanning entry META-INF/versions/9/module-info.class from jar file:///opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1319925543506767746.dir/webapp/WEB-INF/lib/log4j-api-2.11.0.jar, java.lang.RuntimeException: Error scanning entry META-INF/versions/9/org/apache/logging/log4j/util/internal/DefaultObjectInputFilter.class from jar file:///opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1319925543506767746.dir/webapp/WEB-INF/lib/log4j-api-2.11.0.jar, java.lang.RuntimeException: Error scanning entry META-INF/versions/9/org/apache/logging/log4j/util/StackLocator.class from jar file:///opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1319925543506767746.dir/webapp/WEB-INF/lib/log4j-api-2.11.0.jar, java.lang.RuntimeException: Error scanning entry META-INF/versions/9/org/apache/logging/log4j/util/ProcessIdUtil.class from jar file:///opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1319925543506767746.dir/webapp/WEB-INF/lib/log4j-api-2.11.0.jar]
	at org.eclipse.jetty.annotations.AnnotationConfiguration.scanForAnnotations(AnnotationConfiguration.java:534)
	at org.eclipse.jetty.annotations.AnnotationConfiguration.configure(AnnotationConfiguration.java:447)
	at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:494)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1361)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:499)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:147)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:452)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:561)
	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:422)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:389)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1516)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1441)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:214)
	at org.eclipse.jetty.start.Main.start(Main.java:457)
	at org.eclipse.jetty.start.Main.main(Main.java:75)
Caused by: 
MultiException[java.lang.RuntimeException: Error scanning entry META-INF/versions/9/module-info.class from jar file:///opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1319925543506767746.dir/webapp/WEB-INF/lib/log4j-api-2.11.0.jar, java.lang.RuntimeException: Error scanning entry META-INF/versions/9/org/apache/logging/log4j/util/internal/DefaultObjectInputFilter.class from jar file:///opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1319925543506767746.dir/webapp/WEB-INF/lib/log4j-api-2.11.0.jar, java.lang.RuntimeException: Error scanning entry META-INF/versions/9/org/apache/logging/log4j/util/StackLocator.class from jar file:///opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1319925543506767746.dir/webapp/WEB-INF/lib/log4j-api-2.11.0.jar, java.lang.RuntimeException: Error scanning entry META-INF/versions/9/org/apache/logging/log4j/util/ProcessIdUtil.class from jar file:///opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1319925543506767746.dir/webapp/WEB-INF/lib/log4j-api-2.11.0.jar]
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:893)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
Suppressed: 
	|java.lang.RuntimeException: Error scanning entry META-INF/versions/9/org/apache/logging/log4j/util/internal/DefaultObjectInputFilter.class from jar file:///opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1319925543506767746.dir/webapp/WEB-INF/lib/log4j-api-2.11.0.jar
	|	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:906)
	|	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	|	at java.lang.Thread.run(Thread.java:745)
	|Caused by: 
	|java.lang.IllegalArgumentException
	|	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	|	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	|	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	|	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:977)
	|	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:958)
	|	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:902)
	|	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	|	at java.lang.Thread.run(Thread.java:745)
Suppressed: 
	|java.lang.RuntimeException: Error scanning entry META-INF/versions/9/org/apache/logging/log4j/util/StackLocator.class from jar file:///opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1319925543506767746.dir/webapp/WEB-INF/lib/log4j-api-2.11.0.jar
	|	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:906)
	|	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	|	at java.lang.Thread.run(Thread.java:745)
	|Caused by: 
	|java.lang.IllegalArgumentException
	|	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	|	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	|	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	|	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:977)
	|	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:958)
	|	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:902)
	|	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	|	at java.lang.Thread.run(Thread.java:745)
Suppressed: 
	|java.lang.RuntimeException: Error scanning entry META-INF/versions/9/org/apache/logging/log4j/util/ProcessIdUtil.class from jar file:///opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1319925543506767746.dir/webapp/WEB-INF/lib/log4j-api-2.11.0.jar
	|	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:906)
	|	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	|	at java.lang.Thread.run(Thread.java:745)
	|Caused by: 
	|java.lang.IllegalArgumentException
	|	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	|	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	|	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	|	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:977)
	|	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:958)
	|	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:902)
	|	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	|	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	|	at java.lang.Thread.run(Thread.java:745)
Caused by: 
java.lang.RuntimeException: Error scanning entry META-INF/versions/9/module-info.class from jar file:///opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1319925543506767746.dir/webapp/WEB-INF/lib/log4j-api-2.11.0.jar
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:906)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
Caused by: 
java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:977)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:958)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:902)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
2018-05-03 20:20:09.640:INFO:oejs.AbstractConnector:main: Started ServerConnector@456e902{HTTP/1.1,[http/1.1]}{localhost:8082}
2018-05-03 20:20:09.641:INFO:oejs.Server:main: Started @10135ms
root@ussh58dd0:/opt/gluu/jetty/identity/logs# 

```

**Comment by mzico** [comment]
@yurem : any idea?

**Comment by yurem** [comment]
I think we can close it because current version 3.1.5
