### ISSUE TITLE
Post-setup script for adding 'shibb' failing...

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#442]
```
root@:/install/community-edition-setup# python post-setup-add-components.py -addshib
Installing Shibboleth ...
Traceback (most recent call last):
  File "post-setup-add-components.py", line 124, in <module>
    installSaml()
  File "post-setup-add-components.py", line 61, in installSaml
    setupObj.calculate_selected_aplications_memory()
  File "/install/community-edition-setup/setup.py", line 3264, in calculate_selected_aplications_memory
    self.calculate_aplications_memory(self.application_max_ram, self.jetty_app_configuration, installedComponents)
  File "/install/community-edition-setup/setup.py", line 3215, in calculate_aplications_memory
    allowedMemory = int(round(allowedRatio * int(application_max_ram)))
TypeError: int() argument must be a string or a number, not 'NoneType'
root@didp:/install/community-edition-setup#
```

**Comment by mbaser** [comment]
I could not replicate this issue: gluu-server-3.1.3 on CentOS-7

**Comment by syntrydy** [comment]
@mbaser  it seems that he encounter that behavior on Ubuntu

**Comment by mzico** [comment]
@madumlao : Yes.. @syntrydy is correct. If you want I can give you the access to our Dev machine where I was trying to install shibboleth.

**Comment by mbaser** [comment]
It is due to missing entry of `application_max_ram` in `setup.properties.last` since the server is upgraded from 2.4.4 to 3.1.3. `setup.properties.last` also misses other entries to install shib.

**Comment by mzico** [comment]
Reopening... idp metadata can't generate hostname. Provided info in chat.
