### ISSUE TITLE
Nothing there after install

### ISSUE THREAD

**Issue by whiteadam** [GluuFederation/community-edition-setup#5]
Hey guys,

I followed the instructions at  http://www.gluu.org/docs/admin-guide/installation/centos/ to install Gluu CE, but when I go to the server URL, I get redirects to /identity, but there's nothing there.

Any ideas? Error log below:

```
1:54:19 11/13/14 log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /logs/oxauth_persistence_ldap_statistics.log (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:142)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:289)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:163)
	at org.apache.log4j.DailyRollingFileAppender.activateOptions(DailyRollingFileAppender.java:215)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:256)
	at org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:220)
	at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:150)
	at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:163)
	at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:425)
	at org.apache.log4j.xml.DOMConfigurator.parseCategory(DOMConfigurator.java:345)
	at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:827)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:712)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:618)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:470)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:122)
	at org.apache.log4j.Logger.getLogger(Logger.java:117)
	at org.xdi.oxauth.model.util.JwtUtil.<clinit>(JwtUtil.java:84)
	at org.xdi.oxauth.model.crypto.signature.RSAPrivateKey.toJSONObject(RSAPrivateKey.java:57)
	at org.xdi.oxauth.model.crypto.Key.toJSONObject(Key.java:102)
	at org.xdi.oxauth.util.KeyGenerator.generateRS256Keys(KeyGenerator.java:45)
	at org.xdi.oxauth.util.KeyGenerator.main(KeyGenerator.java:18)
log4j:ERROR Either File or DatePattern options are not set for appender [OX_PERSISTENCE_LDAP_STATISTICS_FILE].
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /logs/oxauth.log (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:142)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:289)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:163)
	at org.apache.log4j.DailyRollingFileAppender.activateOptions(DailyRollingFileAppender.java:215)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:256)
	at org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:220)
	at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:150)
	at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:163)
	at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:425)
	at org.apache.log4j.xml.DOMConfigurator.parseRoot(DOMConfigurator.java:394)
	at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:829)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:712)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:618)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:470)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:122)
	at org.apache.log4j.Logger.getLogger(Logger.java:117)
	at org.xdi.oxauth.model.util.JwtUtil.<clinit>(JwtUtil.java:84)
	at org.xdi.oxauth.model.crypto.signature.RSAPrivateKey.toJSONObject(RSAPrivateKey.java:57)
	at org.xdi.oxauth.model.crypto.Key.toJSONObject(Key.java:102)
	at org.xdi.oxauth.util.KeyGenerator.generateRS256Keys(KeyGenerator.java:45)
	at org.xdi.oxauth.util.KeyGenerator.main(KeyGenerator.java:18)
log4j:ERROR Either File or DatePattern options are not set for appender [FILE].

21:58:03 11/13/14 Error running command : /usr/sbin/service httpd stop
21:58:03 11/13/14 Traceback (most recent call last):
  File "./setup.py", line 228, in run
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1234, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

21:58:03 11/13/14 Error running command : /usr/sbin/service httpd start
21:58:03 11/13/14 Traceback (most recent call last):
  File "./setup.py", line 228, in run
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1234, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by joelself** [comment]
Has this issue been resolved somewhere or somehow? I just ran into it trying to run setup on Ubuntu.

**Comment by nynymike** [comment]
New version is coming out tomorrow.  We actually removed this option.

**Comment by joelself** [comment]
Wait, do you mean a new version of Gluu CE or just a new version of setup.py?

**Comment by willow9886** [comment]
we've released Gluu Server 2.1 a few week ago. 2.2 is on the way by end of April. I'm going to close this issue for now.

**Comment by datacarl** [comment]
Hi!

I followed the [centos installation instructions](http://www.gluu.org/docs/admin-guide/deployment/centos/) and ran into the same problem.

The root url works
```
GLUU.[root@ce community-edition-setup]# curl -k https://ce.gluu.info
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://ce.gluu.info/identity/">here</a>.</p>
<hr>
<address>Apache Server at ce.gluu.info Port 443</address>
</body></html>
```

But there is nothing at /identity
```GLUU.[root@ce community-edition-setup]# curl -k https://ce.gluu.info/identity/
<html><head><meta http-equiv="Refresh" content="0; URL=login.htm"/></head></html>```

I seem to have a very similar error log if that's relevant.
```
22:56:45 05/26/15 log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /logs/oxauth_persistence_ldap_statistics.log (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:142)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:289)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:163)
	at org.apache.log4j.DailyRollingFileAppender.activateOptions(DailyRollingFileAppender.java:215)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:256)
	at org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:220)
	at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:150)
	at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:163)
	at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:425)
	at org.apache.log4j.xml.DOMConfigurator.parseCategory(DOMConfigurator.java:345)
	at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:827)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:712)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:618)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:470)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:122)
	at org.apache.log4j.Logger.getLogger(Logger.java:117)
	at org.xdi.oxauth.model.util.JwtUtil.<clinit>(JwtUtil.java:84)
	at org.xdi.oxauth.model.crypto.signature.RSAPrivateKey.toJSONObject(RSAPrivateKey.java:57)
	at org.xdi.oxauth.model.crypto.Key.toJSONObject(Key.java:112)
	at org.xdi.oxauth.util.KeyGenerator.generateRS256Keys(KeyGenerator.java:66)
	at org.xdi.oxauth.util.KeyGenerator.main(KeyGenerator.java:31)
log4j:ERROR Either File or DatePattern options are not set for appender [OX_PERSISTENCE_LDAP_STATISTICS_FILE].
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /logs/oxauth.log (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:142)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:289)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:163)
	at org.apache.log4j.DailyRollingFileAppender.activateOptions(DailyRollingFileAppender.java:215)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:256)
	at org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:220)
	at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:150)
	at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:163)
	at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:425)
	at org.apache.log4j.xml.DOMConfigurator.parseRoot(DOMConfigurator.java:394)
	at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:829)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:712)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:618)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:470)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:122)
	at org.apache.log4j.Logger.getLogger(Logger.java:117)
	at org.xdi.oxauth.model.util.JwtUtil.<clinit>(JwtUtil.java:84)
	at org.xdi.oxauth.model.crypto.signature.RSAPrivateKey.toJSONObject(RSAPrivateKey.java:57)
	at org.xdi.oxauth.model.crypto.Key.toJSONObject(Key.java:112)
	at org.xdi.oxauth.util.KeyGenerator.generateRS256Keys(KeyGenerator.java:66)
	at org.xdi.oxauth.util.KeyGenerator.main(KeyGenerator.java:31)
log4j:ERROR Either File or DatePattern options are not set for appender [FILE].

22:59:12 05/26/15 Certificate stored in file </etc/certs/opendj.crt>

22:59:12 05/26/15 Certificate was added to keystore
```

**Comment by mzico** [comment]
@datacarl : Please check if 443 and 80 ports are open in that VM which you are using.

**Comment by datacarl** [comment]
@mzico thanks, they are. It's empty when I curl it from within the VM too.

**Comment by nynymike** [comment]
This thread needs to move to https://support.gluu.org

github is for bug tracking / feature requests only

**Comment by datacarl** [comment]
@nynymike ok, sorry, I just saw this issue and thought it was similar. Didnt see the support forums until now, thanks for the link! Tried to create an account but I get 500 errors (just FYI). Will post there later.

**Comment by willow9886** [comment]
@datacarl I was just able to register an account successfully. I believe you already have an account registered with your lookback.io email address.
