### ISSUE TITLE
UMA org units must be created during installation 

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/community-edition-setup#528]
UMA org units must be created during installation. For example cleaner failed with message `The search base entry 'ou=pct,ou=uma,o=gluu' does not exist` however it's expected that setup creates `ou=pct,ou=uma,o=gluu`.

```
2019-04-16 14:00:05,356 ERROR [Thread-8691] [org.gluu.oxauth.service.CleanerTimer] (CleanerTimer.java:172) - Failed to process clean up for 
baseDn: ou=pct,ou=uma,o=gluu
org.gluu.persist.exception.EntryPersistenceException: Failed to find entries with baseDN: ou=pct,ou=uma,o=gluu, filter: (&(oxDeletable=true)
(oxAuthExpiration<=20190416130005.335Z))
        at org.gluu.persist.ldap.impl.LdapEntryManager.findEntries(LdapEntryManager.java:402) ~[oxcore-persistence-ldap-4.0.0-SNAPSHOT.jar:?
]
        at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
        at org.gluu.persist.EntityManager$PersistenceEntryManager$1948486608$Proxy$_$$_WeldClientProxy.findEntries(Unknown Source) ~[weld-co
re-impl-3.0.5.Final.jar:?]
        at org.gluu.oxauth.service.CleanerTimer.processImpl(CleanerTimer.java:166) [classes/:?]
        at org.gluu.oxauth.service.CleanerTimer$Proxy$_$$_WeldSubclass.processImpl(Unknown Source) [classes/:?]
        at org.gluu.oxauth.service.CleanerTimer.process(CleanerTimer.java:129) [classes/:?]
        at org.gluu.oxauth.service.CleanerTimer$Proxy$_$$_WeldSubclass.process$$super(Unknown Source) [classes/:?]
        at sun.reflect.GeneratedMethodAccessor224.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
        at org.gluu.service.cdi.async.AsynchronousInterceptor$1.get(AsynchronousInterceptor.java:36) [oxcore-service-4.0.0-SNAPSHOT.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: org.gluu.persist.exception.operation.SearchException: Failed to scroll to specified start
        at org.gluu.persist.ldap.operation.impl.LdapOperationsServiceImpl.searchImpl(LdapOperationsServiceImpl.java:403) ~[oxcore-persistence-ldap-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.persist.ldap.operation.impl.LdapOperationsServiceImpl.search(LdapOperationsServiceImpl.java:305) ~[oxcore-persistence-ldap-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.persist.ldap.impl.LdapEntryManager.findEntries(LdapEntryManager.java:395) ~[oxcore-persistence-ldap-4.0.0-SNAPSHOT.jar:?]
        ... 18 more
Caused by: com.unboundid.ldap.sdk.LDAPSearchException: The search base entry 'ou=pct,ou=uma,o=gluu' does not exist
        at com.unboundid.ldap.sdk.LDAPConnection.search(LDAPConnection.java:3772) ~[unboundid-ldapsdk-4.0.7.jar:4.0.7]
        at org.gluu.persist.ldap.operation.impl.LdapOperationsServiceImpl.searchImpl(LdapOperationsServiceImpl.java:373) ~[oxcore-persistenc:
```

**Comment by yuriyz** [comment]
Fixed in master
