### ISSUE TITLE
Python error in setup.py on Ubuntu 14.04

### ISSUE THREAD

**Issue by bhourigan** [GluuFederation/community-edition-setup#53]
I fetched master.zip from github but the installation script is still giving me an error - here's the output:

```
GLUU.root@ce:~/community-edition-setup-master# python setup.py -f setup.properties -n

Ooops...  file not found for setup properties.


Installing Gluu Server...

For more info see:
  ./setup.log
  ./setup_error.log


** All clear text passwords contained in ./setup.properties.last.

Traceback (most recent call last):
  File "setup.py", line 1543, in <module>
    print '\n%s\n' % `installObject`
  File "setup.py", line 276, in __repr__
    + 'Install oxAuth RP'.ljust(30) + `self.components['oxauth_rp']['enabled']`.rjust(35) + "\n"
AttributeError: 'NoneType' object has no attribute 'rjust'
```

Contents of setup.properties, minus comments
```
ip=localhost
hostname=login.foobar.org
orgName=Foobar
countryCode=US
city=Mountain View
state=CA
jksPass=
ldapPass=
inumOrg=
inumAppliance=
```

**Comment by nynymike** [comment]
I'm working on some fixes... why aren't you using the packages? We just shipped 2.3.3 two days ago!

**Comment by bhourigan** [comment]
I'm following the installation instructions documented here - http://www.gluu.org/docs/admin-guide/deployment/ubuntu/

It says to first install via package, and then run setup.py. Is this incorrect or obsolete?

**Comment by nynymike** [comment]
I'm removing the comment about downloading the latest install script from Github. Its best to use the script we QA'd as part of the release. Also, for any problem with installation, please register and post the question on our support site: https://support.gluu.org

**Comment by bhourigan** [comment]
There's a bug in the script, which this issue is related to. I'm not asking for support I am reporting a bug.

**Comment by nynymike** [comment]
Its not a bug. Your setup.properties are wrong! If you run the script interactively and answer the 10 questions it will generate a full set of properties which you can inspect and use for future installations. The properties feature is not really supposed to be used with an initial installation. BTW, are you working on FIDO U2F?

**Comment by klausstake** [comment]
It is a bug. I have the same problem. When I answer the fourth question, then I get the same error message.

I tried to install on Cent OS using this documentation:
http://www.gluu.org/docs/admin-guide/deployment/centos/

Regards,
Klaus

**Comment by zamilskhan** [comment]
Hello, I tried to reproduce your issue but failed. The output is as follows:
```
[root@centos ~]# service gluu-server24 start
Starting Gluu server, please wait...

[root@centos ~]# service gluu-server24 login
gluu-server24 is running...
logging in...
Welcome to the Gluu Server!
GLUU.[root@localhost ~]# cd /install/community-edition-setup/
GLUU.[root@localhost community-edition-setup]# ./setup.py 

Installing Gluu Server...

For more info see:
  ./setup.log  
  ./setup_error.log


** All clear text passwords contained in ./setup.properties.last.

Enter IP Address [192.168.122.20] : 
Enter hostname [localhost] : centos.gluu.info
Enter your city or locality : 
Enter your state or province two letter code : GR
Enter two letter Country Code : 
Enter Organization Name : test
Enter email address for support at your organization : mail@test.org
Enter maximum RAM for tomcat in MB [1536] : 
Optional: enter password for oxTrust and LDAP superuser [uoxtVxPwzG39] : 
Install oxAuth OAuth2 Authorization Server? [Yes] : 
Install oxTrust Admin UI? [Yes] : 
Install Gluu OpenDJ LDAP Server? [Yes] : 
Install Apache HTTPD Server [Yes] : 
Install Shibboleth 2 SAML IDP? [No] : yes
Install Asimba SAML Proxy? [No] : 
Install CAS? [No] : yes
Install oxAuth RP? [No] : 

hostname                                         centos.gluu.info
orgName                                                      test
os                                                         centos
city                                                        
state                                                          
countryCode                                                    
support email                                       mail@test.org
tomcat max ram                                               1536
Admin Pass                                                 
Install oxAuth                                               True
Install oxTrust                                              True
Install LDAP                                                 True
Install Apache 2 web server                                  True
Install Shibboleth 2 SAML IDP                                True
Install Asimba SAML Proxy                                   False
Install CAS                                                  True
Install oxAuth RP                                           False


Proceed with these values [Y|n] Y

 Gluu Server installation successful! Point your broswer to https://centos.gluu.info
```

**Comment by nynymike** [comment]
Github is not for support. Please regiser and post your issue on https://support.gluu.org  If an issue proves to be a bug, we track it here.
