### ISSUE TITLE
Gluu 4.0 QA - Basic_lock script not working

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/community-edition-setup#552]
Steps to reproduce:
1. Enable basic_lock script and change oxtrust default authentication to basic_lock
2. Try to login to oxtrust admin UI

Expected Results: User should be allowed to enter credentials
Actual - 
![image](https://user-images.githubusercontent.com/21104811/60775828-d656fc00-a0f4-11e9-8b1d-b08c143eeae0.png)

Error in Script

```
org.gluu.exception.PythonException: Failed to load python file 'java.io.ByteArrayInputStream@35193153'
	at org.gluu.service.PythonService.loadPythonScript(PythonService.java:184)
	at org.gluu.service.PythonService$Proxy$_$$_WeldClientProxy.loadPythonScript(Unknown Source)
	at org.gluu.service.custom.script.CustomScriptManager.createExternalTypeFromStringWithPythonException(CustomScriptManager.java:390)
	at org.gluu.service.custom.script.CustomScriptManager$Proxy$_$$_WeldSubclass.createExternalTypeFromStringWithPythonException(Unknown Source)
	at org.gluu.service.custom.script.CustomScriptManager.createExternalType(CustomScriptManager.java:358)
	at org.gluu.service.custom.script.CustomScriptManager.reloadCustomScriptConfigurations(CustomScriptManager.java:268)
	at org.gluu.service.custom.script.CustomScriptManager.reloadImpl(CustomScriptManager.java:157)
	at org.gluu.service.custom.script.CustomScriptManager.reload(CustomScriptManager.java:144)
	at org.gluu.service.custom.script.CustomScriptManager.reloadTimerEvent(CustomScriptManager.java:120)
	at org.gluu.service.custom.script.CustomScriptManager$Proxy$_$$_WeldSubclass.reloadTimerEvent(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor105.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
	at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:168)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
	at org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:159)
	at org.jboss.weld.manager.BeanManagerImpl.fireEvent(BeanManagerImpl.java:632)
	at org.jboss.weld.util.ForwardingBeanManager.fireEvent(ForwardingBeanManager.java:104)
	at org.gluu.service.timer.TimerJob.execute(TimerJob.java:39)
	at org.gluu.service.timer.JobExecutionDelegate.execute(JobExecutionDelegate.java:31)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: Traceback (most recent call last):
  File "basic_lock.py", line 14, in <module>
ImportError: No module named site

	at org.python.core.Py.ImportError(Py.java:334)
	at org.python.core.imp.import_logic(imp.java:913)
	at org.python.core.imp.import_module_level(imp.java:970)
	at org.python.core.imp.importName(imp.java:1057)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:450)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1149)
	at org.python.core.imp.importFrom(imp.java:1124)
	at org.python.pycode._pyx30.f$0(basic_lock.py:24)
```

Setup Details : CentOs7.3 with couchbase as backend

**Comment by yurem** [comment]
Fixed https://github.com/GluuFederation/community-edition-setup/blob/master/static/extension/person_authentication/BasicLockAccountExternalAuthenticator.py
