### ISSUE TITLE
Gluu 4.0 QA - fido2 not working 

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/community-edition-setup#554]
Steps to reproduce:
1. Enable Fido2 custom authentication script and change oxtrust default authentication to use Fido2
2. Login to oxtrust

Expected result: User should be allowed to login with fido2

Actual
After entering credentials, user gets OOPS error, refer screenshot
![image](https://user-images.githubusercontent.com/21104811/60854972-ff988a80-a1cf-11e9-8a40-eb558d50ced0.png)

Error in logs
java:124) - cosePublicKey {"1":2,"3":-7,"-1":1,"-2":"jd5BKlTMD0zCpUz6ZWthh2qp3tUmfa82k2BLVChiKRM=","-3":"tnhmNdRej5UTFCVjYWkz7GjRDGFY9mov5XqFXNxchFA="}
2019-07-04 03:50:39,612 INFO  [qtp985655350-17] [org.gluu.oxauth.fido2.certification.CertificationKeyStoreUtils] (CertificationKeyStoreUtils.java:82) - No metadata for authenticator 77010bd7212a4fc9b236d2ca5e9d4084. Attempting to contact MDS
2019-07-04 03:50:39,613 ERROR [qtp985655350-17] [org.gluu.oxauth.fido2.service.Fido2RpExceptionHandler] (Fido2RpExceptionHandler.java:33) - Handled Fido2 RP exception
org.gluu.oxauth.fido2.exception.Fido2RPRuntimeException: Authenticator not in TOC aaguid 77010bd7-212a-4fc9-b236-d2ca5e9d4084
        at org.gluu.oxauth.fido2.service.mds.MdsService.fetchMetadata(MdsService.java:91) ~[oxauth-fido2-server-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.oxauth.fido2.service.mds.MdsService$Proxy$_$$_WeldClientProxy.fetchMetadata(Unknown Source) ~[oxauth-fido2-server-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.oxauth.fido2.certification.CertificationKeyStoreUtils.getCertificates(CertificationKeyStoreUtils.java:83) ~[oxauth-fido2-server-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.oxauth.fido2.certification.CertificationKeyStoreUtils.populateTrustManager(CertificationKeyStoreUtils.java:97) ~[oxauth-fido2-server-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.oxauth.fido2.certification.CertificationKeyStoreUtils$Proxy$_$$_WeldClientProxy.populateTrustManager(Unknown Source) ~[oxauth-fido2-server-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.oxauth.fido2.service.processors.impl.PackedAttestationProcessor.process(PackedAttestationProcessor.java:84) ~[oxauth-fido2-server-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.oxauth.fido2.service.processors.impl.PackedAttestationProcessor$Proxy$_$$_WeldClientProxy.process(Unknown Source) ~[oxauth-fido2-server-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.oxauth.fido2.service.verifier.AuthenticatorAttestationVerifier.verifyAuthenticatorAttestationResponse(AuthenticatorAttestationVerifier.java:85) ~[oxauth-fido2-server-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.oxauth.fido2.service.verifier.AuthenticatorAttestationVerifier$Proxy$_$$_WeldClientProxy.verifyAuthenticatorAttestationResponse(Unknown Source) ~[oxauth-fido2-server-4.0.0-SNAPSHOT.jar:?]

Fido2 Key Used: Biopass Fetia https://www.ftsafe.com/onlinestores/product?id=3
Gluu 4.0 Centos7.3 couchbase db

**Comment by sahiliamsso** [comment]
@yurem - any update? It is still not working in beta build

**Comment by yurem** [comment]
I've checked the issue is in missing toc.jwt file. We can't redistribute TOC files. You should download it manually and put into `/etc/gluu/conf/fido2/mds/toc/` folder.

**Comment by willow9886** [comment]
@yurem @sahiliamsso do we need to update our documentation to make this clear?

**Comment by yurem** [comment]
I added pull request https://github.com/GluuFederation/docs-ce-prod/pull/207

**Comment by sahiliamsso** [comment]
I just added toc.jwt file and restarted oxauth
```
019-07-30 23:58:48,825 INFO  [qtp1749186397-13] [org.gluu.oxauth.fido2.certification.CertificationKeyStoreUtils] (CertificationKeyStoreUtils.java:82) - No metadata for authenticator 77010bd7212a4fc9b236d2ca5e9d4084. Attempting to contact MDS
2019-07-30 23:58:48,837 ERROR [qtp1749186397-13] [org.gluu.oxauth.fido2.service.Fido2RpExceptionHandler] (Fido2RpExceptionHandler.java:33) - Handled Fido2 RP exception
org.gluu.oxauth.fido2.exception.Fido2RPRuntimeException: Fido2 MDS access token should be set
        at org.gluu.oxauth.fido2.service.mds.MdsService.fetchMetadata(MdsService.java:101) ~[oxauth-fido2-server-4.0.b1.jar:?]
        at org.gluu.oxauth.fido2.service.mds.MdsService$Proxy$_$$_WeldClientProxy.fetchMetadata(Unknown Source) ~[oxauth-fido2-server-4.0.b1.jar:?]
        at org.gluu.oxauth.fido2.certification.CertificationKeyStoreUtils.getCertificates(CertificationKeyStoreUtils.java:83) ~[oxauth-fido2-server-4.0.b1.jar:?]
        at org.gluu.oxauth.fido2.certification.CertificationKeyStoreUtils.populateTrustManager(CertificationKeyStoreUtils.java:97) ~[oxauth-fido2-server-4.0.b1.jar:?]
        at org.gluu.oxauth.fido2.certification.CertificationKeyStoreUtils$Proxy$_$$_WeldClientProxy.populateTrustManager(Unknown Source) ~[oxauth-fido2-server-4.0.b1.jar:?]
        at org.gluu.oxauth.fido2.service.processors.impl.PackedAttestationProcessor.process(PackedAttestationProcessor.java:84) ~[oxauth-fido2-server-4.0.b1.jar:?]
        at org.gluu.oxauth.fido2.service.processors.impl.PackedAttestationProcessor$Proxy$_$$_WeldClientProxy.process(Unknown Source) ~[oxauth-fido2-server-4.0.b1.jar:?]
        at org.gluu.oxauth.fido2.service.verifier.AuthenticatorAttestationVerifier.verifyAuthenticatorAttestationResponse(AuthenticatorAttestationVerifier.java:85) ~[oxauth-fido2-server-4.0.b1.jar:?]
        at org.gluu.oxauth.fido2.service.verifier.AuthenticatorAttestationVerifier$Proxy$_$$_WeldClientProxy.verifyAuthenticatorAttestationResponse(Unknown Source) ~[oxauth-fido2-server-4.0.b1.jar:?]
        at org.gluu.oxauth.fido2.ws.rs.service.AttestationService.verify(AttestationService.java:133) ~[oxauth-fido2-server-4.0.b1.jar:?]
        at org.gluu.oxauth.fido2.ws.rs.service.AttestationService$Proxy$_$$_WeldClientProxy.verify(Unknown Source) ~[oxauth-fido2-server-4.0.b1.jar:?]
        at org.gluu.oxauth.fido2.ws.rs.controller.AttestationController.verify(AttestationController.java:73) ~[oxauth-fido2-server-4.0.b1.jar:?]
        at org.gluu.oxauth.fido2.ws.rs.controller.AttestationController$Proxy$_$$_WeldClientProxy.verify(Unknown Source) ~[oxauth-fido2-server-4.0.b1.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
```

**Comment by sahiliamsso** [comment]
@yurem - I was able to login first time with Fido2 key but received error on next login
![image](https://user-images.githubusercontent.com/21104811/63626120-d2f9d000-c5cf-11e9-8a6c-a690ddee14bf.png)

```
0) - Fido2. Prepare for step 2. Call Fido2 endpoint in order to start assertion flow
2019-08-23 21:58:17,139 INFO  [qtp105704967-17] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:240) - Fido2. Prepare for step 2. Successfully start flow with next requests.
2019-08-23 21:58:17,139 INFO  [qtp105704967-17] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:240) - fido2_assertion_request: '{"challenge":"ep7e51e88M7k_rcL0n_i52uto7aW43Xo_wz3O3e8-XM","user":{"name":"admin"},"allowCredentials":[{"type":"public-key","transports":["usb","ble","nfc"],"id":"oF2jgZhZZ22TGzl8RqT-Pp8A1yXaEMlZGG9ThON6-ROoIQSTXDDNL5Od-MZ6KiQ0PjqCOuEkPKCSNU142pWhGDK2_9AcKlcWk963ZLfnfH6DZQWENwjqxQff40Plm4J3"}],"userVerification":"required","status":"ok","errorMessage":""}'
2019-08-23 21:58:17,140 INFO  [qtp105704967-17] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:240) - fido2_attestation_request: 'None'
2019-08-23 21:58:17,140 DEBUG [qtp105704967-17] [org.gluu.oxauth.service.external.ExternalAuthenticationService] (ExternalAuthenticationService.java:263) - Executing python 'getExtraParametersForStep' authenticator method
```
