### ISSUE TITLE
SEVERE: Exception sending context destroyed event to listener instance of class 

### ISSUE THREAD

**Issue by rngadam** [GluuFederation/community-edition-setup#60]
gluu-server 2.3.3-1 on Ubuntu 14.04

```service gluu-server restart``` fails:

```
# service gluu-server restart
Shutting down Gluu Server...
Stopping Apache...
Failed
Stopping Tomcat...
Failed
Stopping Memcached...
Failed
Stopping OpendDJ...
Failed
```

logs show:

```
==> /opt/apache-tomcat-7.0.55/logs/localhost.2015-09-07.log <==
Sep 07, 2015 4:26:19 AM org.apache.catalina.core.ApplicationContext log
INFO: Closing Spring root WebApplicationContext
Sep 07, 2015 4:26:19 AM org.apache.catalina.core.StandardContext listenerStop
SEVERE: Exception sending context destroyed event to listener instance of class com.sun.faces.config.ConfigureListener
java.lang.NullPointerException
        at javax.faces.component.UIViewRoot.getViewMap(UIViewRoot.java:1542)
        at com.sun.faces.config.InitFacesContext.release(InitFacesContext.java:237)
        at com.sun.faces.config.ConfigureListener.contextDestroyed(ConfigureListener.java:352)
        at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:5033)
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5685)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1591)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1580)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by nynymike** [comment]
We will take a look. I'm not sure restart is a good idea. We may just remove the feature. Within the gluu server you might want to restart a service, like tomcat or opendj, but I don't think restarting all the processes within the gluu-server is that useful.

**Comment by ganesh-at-wiw** [comment]
Restart seems buggy. But service stop and start separately works fine over many cycles.

root@testidp:~# service gluu-server restart
Shutting down Gluu Server...
Stopping Apache...
OK
Stopping Tomcat...
OK
Stopping Memcached...
OK
Stopping OpendDJ...
OK

Port address(es) 1689
443
4444
8009
1389
80 already in use,
Please stop the service(s) listening on one of 1689
443
4444
8009
1389
80 ports and execute /etc/init.d/gluu-server start
root@testidp:~# service gluu-server stop
gluu-server is not running
root@testidp:~# service gluu-server start
Starting Gluu server, please wait...

root@testidp:~# service gluu-server stop
Shutting down Gluu Server...
Stopping Apache...
OK
Stopping Tomcat...
OK
Stopping Memcached...
OK
Stopping OpendDJ...
OK

root@testidp:~# service gluu-server start
Starting Gluu server, please wait...

root@testidp:~# service gluu-server stop
Shutting down Gluu Server...
Stopping Apache...
OK
Stopping Tomcat...
OK
Stopping Memcached...
OK
Stopping OpendDJ...
OK

root@testidp:~# 


Also, running stop twice confirms that it actually stopped services.
root@testidp:~# service gluu-server stop
Shutting down Gluu Server...
Stopping Apache...
OK
Stopping Tomcat...
OK
Stopping Memcached...
OK
Stopping OpendDJ...
OK

root@testidp:~# service gluu-server stop
gluu-server is not running
root@testidp:~#

**Comment by nynymike** [comment]
Then we should move the `restart` command.
