### ISSUE TITLE
Shibboleth failing to load in 4.2.0 final with Debian 10

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#712]
![Capture](https://user-images.githubusercontent.com/7156097/90811275-f2623080-e2e9-11ea-8dd9-d37c259bfff3.PNG)

- `idp` startup log saying below: 

```
tion-api-2.0.1.Final.jar!/javax/validation/valueextraction/ValueExtractor.class
2020-08-20 15:08:43.961:WARN:oeja.AnnotationParser:qtp705265961-20: javax.validation.valueextraction.ValueExtractorDeclarationException scanned from multiple locations: jar:file:///opt/jetty-9.4/temp/jetty-localhost-8086-idp_war-_idp-any-5983857348396641335.dir/webapp/WEB-INF/lib/jakarta.validation-api-2.0.2.jar!/javax/validation/valueextraction/ValueExtractorDeclarationException.class, jar:file:///opt/jetty-9.4/temp/jetty-localhost-8086-idp_war-_idp-any-5983857348396641335.dir/webapp/WEB-INF/lib/validation-api-2.0.1.Final.jar!/javax/validation/valueextraction/ValueExtractorDeclarationException.class
2020-08-20 15:08:43.961:WARN:oeja.AnnotationParser:qtp705265961-20: javax.validation.valueextraction.ValueExtractorDefinitionException scanned from multiple locations: jar:file:///opt/jetty-9.4/temp/jetty-localhost-8086-idp_war-_idp-any-5983857348396641335.dir/webapp/WEB-INF/lib/jakarta.validation-api-2.0.2.jar!/javax/validation/valueextraction/ValueExtractorDefinitionException.class, jar:file:///opt/jetty-9.4/temp/jetty-localhost-8086-idp_war-_idp-any-5983857348396641335.dir/webapp/WEB-INF/lib/validation-api-2.0.1.Final.jar!/javax/validation/valueextraction/ValueExtractorDefinitionException.class
2020-08-20 15:08:44.746:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=2211ms
2020-08-20 15:08:44.767:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@6acdbdf5{Shibboleth Identity Provider,/idp,file:///opt/jetty-9.4/temp/jetty-localhost-8086-idp_war-_idp-any-5983857348396641335.dir/webapp/,UNAVAILABLE}{/opt/gluu/jetty/idp/webapps/idp.war}
java.lang.UnsupportedClassVersionError: org/gluu/idp/externalauth/ShibOxAuthAuthServlet has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at org.eclipse.jetty.webapp.WebAppClassLoader.foundClass(WebAppClassLoader.java:649)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadAsResource(WebAppClassLoader.java:622)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:534)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.eclipse.jetty.util.Loader.loadClass(Loader.java:64)
        at org.eclipse.jetty.webapp.DiscoveredAnnotation.loadClass(DiscoveredAnnotation.java:80)
        at org.eclipse.jetty.webapp.DiscoveredAnnotation.getTargetClass(DiscoveredAnnotation.java:65)
        at org.eclipse.jetty.annotations.WebServletAnnotation.apply(WebServletAnnotation.java:67)
        at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:450)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1407)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:822)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:46)
        at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
        at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:513)
        at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:154)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:173)
        at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:441)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:66)
        at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:784)
        at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:753)
        at org.eclipse.jetty.util.Scanner.scan(Scanner.java:641)
        at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:540)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:146)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:599)
        at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:249)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.server.Server.start(Server.java:407)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.server.Server.doStart(Server.java:371)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$0(XmlConfiguration.java:1888)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1837)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:218)
        at org.eclipse.jetty.start.Main.start(Main.java:491)
        at org.eclipse.jetty.start.Main.main(Main.java:77)
2020-08-20 15:08:44.801:INFO:oejs.AbstractConnector:main: Started ServerConnector@4a94ee4{HTTP/1.1,[http/1.1]}{localhost:8086}
2020-08-20 15:08:44.802:INFO:oejs.Server:main: Started @4707ms
```

- java version: 

```
root@testsaml42debian10:~# find / -name java
/opt/amazon-corretto-8.222.10.1-linux-x64/bin/java
/opt/amazon-corretto-8.222.10.1-linux-x64/jre/bin/java
/opt/jython-2.7.2a/tests/java
root@testsaml42debian10:~#
```

**Comment by yurem** [comment]
Can you run `ps -efH` to double check if we use right java to run this process

**Comment by yurem** [comment]
4.2.1 starts fine. Do we need to check this in 4.2.0?

**Comment by yurem** [comment]
In 4.2.0 I've reproduced it

**Comment by mzico** [comment]
@yurem : Ok, I think we can keep them as they are now then. If anyone require Shibb in Gluu 4.0 under Debian 10, we know the workaround. Thoughts?

**Comment by mzico** [comment]
@yurem : it's fixed with latest debian 10 package in 4.2.0.

**Comment by yurem** [comment]
@mzico can you try latest 4.2.0 package?

**Comment by mzico** [comment]
@yurem : https://github.com/GluuFederation/community-edition-setup/issues/712#issuecomment-687388880
