### ISSUE TITLE
Unable to add post component in Ubuntu 20

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/community-edition-setup#716]
### Describe

while adding any post component in gluu installation in ubuntu 20 gives you following error

```
Traceback (most recent call last):
  File "post-setup-add-components.py", line 92, in <module>
    from ces_current.pylib.generate_properties import generate_properties
  File "/install/community-edition-setup/ces_current/pylib/generate_properties.py", line 28, in <module>
    p = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'
```

 ### Steps to reproduce 
1. try to install oxd component after gluu server installation.
2. python3 post-setup-add-components.py -addpassport

**Comment by mbaser** [comment]
Fixed in commit 1e4fb1f34a9f8fb139b5c1540c96328f8e02c76b
