### ISSUE TITLE
Crash during Install if importing setup.properties

### ISSUE THREAD

**Issue by nathmo** [GluuFederation/community-edition-setup#729]
Hi,
I'm trying to manually setup a Gluu Cluster followings [those instructions](https://gluu.org/docs/gluu-server/installation-guide/cluster/#prerequisites) and while running setup.py on the secondary node I ran into 

`Traceback (most recent call last):
  File "./setup.py", line 6083, in <module>
    GSA.run()
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)    
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/apNPSApplicationManaged.py", line 172, in main
    self._THISFORM.edit()
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/fm_form_edit_loop.py", line 47, in edit
    self.edit_loop()
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/fm_form_edit_loop.py", line 38, in edit_loop
    self._widgets__[self.editw].edit()
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/wgwidget.py", line 447, in edit
    self._edit_loop()
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/wgwidget.py", line 463, in _edit_loop
    self.get_and_use_key_press()
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/wgwidget.py", line 599, in get_and_use_key_press
    self.handle_input(ch)
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/wgwidget.py", line 71, in handle_input
    self.handlers[_input](_input)
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/wgbutton.py", line 97, in h_toggle
    self.when_pressed_function()
  File "/install/community-edition-setup/pylib/tui.py", line 357, in nextButtonPressed
    if not self.parentApp.installObject.calculate_selected_aplications_memory():
  File "./setup.py", line 4409, in calculate_selected_aplications_memory
    return self.calculate_aplications_memory(self.application_max_ram, installedComponents)
  File "./setup.py", line 4369, in calculate_aplications_memory
    if opendj_max_ram < self.opendj_ram:
TypeError: '<' not supported between instances of 'int' and 'str'`

I edited the setup.py file to force the int conversion `self.opendj_ram -> int(self.opendj_ram)` everywhere it was used and the script ran without error

I then ran `iff -l setup.properties setup.properties.last` to see if there were any differences in the file that might mess up the deployment of the cluster as the config are not the same.
I got a difference at theses two places : 
`encoded_oxtrust_admin_password={SSHA}REDACTEDHASH`
`passport_rp_client_cert_alias=REDACTEDHASH_sig_rs512`

Hopefully theses do not matter (may someone from Gluu confirm this ?)

I Installed version 4.2.3

I would like to make PR for the exact fix (assuming the differences in the config are normal and my fix is enough).

**Comment by nathmo** [comment]
I'm quite confused as I can't find the setup.py in the repo. [I believed this was the one](https://github.com/GluuFederation/community-edition-setup/blob/master/setup.py)  I was looking for, but it is only ~300 line long instead of the +4000 on the one I got by installing Gluu-ce using apt install gluu-server under /opt/gluu-server/install/community-edition-setup

**Comment by nynymike** [comment]
We don't provide community support on Github. If you have an issue to raise, you'll need to register and post it on https://gluu.org/booking 

Also, we don't generally have time to answer questions about HA on the community forums. We offer commercial support for customers who need a clustered topology.

**Comment by nathmo** [comment]
Well I tried to fix my own issue and made a PR to fix it but okay.
