### ISSUE TITLE
Error installing Passport with Spanner as persistence

### ISSUE THREAD

**Issue by iromli** [GluuFederation/community-edition-setup#740]
When installing Passport (by adding `--install-passport` arg to `setup.py` command), the installation is failed.

This is the traceback from `stdout`:

```
Traceback (most recent call last):
  File "/opt/dist/app/gcs/google/api_core/grpc_helpers.py", line 73, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/opt/dist/app/gcs/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/dist/app/gcs/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.NOT_FOUND
        details = "Column not found in table gluuApplicationConfiguration: gluuPassportEnabled"
        debug_error_string = "{"created":"@1622834547.620006204","description":"Error received from peer ipv4:139.59.121.170:9010","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Column not found in table gluuApplicationConfiguration: gluuPassportEnabled","grpc_status":5}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./setup.py", line 322, in do_installation
    passportInstaller.start_installation()
  File "/install/community-edition-setup/setup_app/installers/base.py", line 45, in start_installation
    self.update_backend()
  File "/install/community-edition-setup/setup_app/installers/passport.py", line 200, in update_backend
    self.dbUtils.set_configuration('gluuPassportEnabled', 'true')
  File "/install/community-edition-setup/setup_app/utils/db_utils.py", line 349, in set_configuration
    self.spanner.insert_data(table='gluuApplicationConfiguration', columns=["doc_id", component], values=[["oxauth", type_val]])
  File "/install/community-edition-setup/setup_app/utils/spanner.py", line 68, in insert_data
    tr.insert(table, columns=columns, values=values)
  File "/opt/dist/app/gcs/google/cloud/spanner_v1/transaction.py", line 338, in __exit__
    self.commit()
  File "/opt/dist/app/gcs/google/cloud/spanner_v1/transaction.py", line 149, in commit
    response = api.commit(request=request, metadata=metadata,)
  File "/opt/dist/app/gcs/google/cloud/spanner_v1/services/spanner/client.py", line 1346, in commit
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/opt/dist/app/gcs/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/opt/dist/app/gcs/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/opt/dist/app/gcs/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/opt/dist/app/gcs/google/api_core/grpc_helpers.py", line 75, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.NotFound: 404 Column not found in table gluuApplicationConfiguration: gluuPassportEnabled
```

This is (probably) caused by modifying incorrect table (`gluuApplicationConfiguration` instead of `gluuConfiguration`.

**Comment by mbaser** [comment]
@iromli I tested, can you also test and close issue if fixed?
