### ISSUE TITLE
RHEL 8 / Gluu Server 4.2.3 / SCIM not installing 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#753]
SCIM service is not configuring in Gluu Server 4.2.3. 

`setup_error.log` showing: 

```
11:46:14 PM 08/25/2021 Failed to enable unit: Unit file scim.service does not exist.

11:46:14 PM 08/25/2021 Error copying /opt/dist/gluu/scim.war to /opt/gluu/jetty/scim/webapps
11:46:14 PM 08/25/2021 Traceback (most recent call last):
  File "./setup.py", line 1206, in copyFile
    shutil.copy(inFile, destFolder)
  File "/usr/lib64/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/dist/gluu/scim.war'

11:47:41 PM 08/25/2021 *** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
```

**Comment by mbaser** [comment]
Was it rpm container or `gluu_install.py`?

**Comment by mzico** [comment]
@mbaser : rpm container...

**Comment by nikdavnik** [comment]
updated 4.2.3 package, added scim.war
https://repo.gluu.org/rhel/8/gluu-server-4.2.3-rhel8.x86_64.rpm
