### ISSUE TITLE
Required field checks are missing at Setup TUI

### ISSUE THREAD

**Issue by quiver** [GluuFederation/community-edition-setup#754]
## Environment

- Gluu Server 4.2
- OS : Ubuntu 20.04

## Problem

At Setup TUI's "Gathering Information" step([1]), you're required to fill in fields like 

- Hostname
- Support Email

Some fields are required(Support Email, Country Code, etc.), but some fields are optional(e.g. City or Locality).

If you make "City or Locality" field blank and click "Next" at the confirmation step, you can't go on to the next step.

Cntrl-C shows that the script is chalked at `check_properties` method.
See the traceback at the end of this issue.

When I fill in all fields at "Gathering Information", I could successfully finish the setup process.

## How to fix

If "City or Locality" is mandatory, you should validate its existence.

## Cntrl-C Traceback

```
Traceback (most recent call last):
  File "./setup.py", line 6083, in <module>
    GSA.run()
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/apNPSApplicationManaged.py", line 172, in main
    self._THISFORM.edit()
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/fm_form_edit_loop.py", line 47, in edit
    self.edit_loop()
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/fm_form_edit_loop.py", line 38, in edit_loop
    self._widgets__[self.editw].edit()
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/wgwidget.py", line 447, in edit
    self._edit_loop()
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/wgwidget.py", line 463, in _edit_loop
    self.get_and_use_key_press()
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/wgwidget.py", line 599, in get_and_use_key_press
    self.handle_input(ch)
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/wgwidget.py", line 71, in handle_input
    self.handlers[_input](_input)
  File "/usr/local/lib/python3.8/dist-packages/npyscreen/wgbutton.py", line 97, in h_toggle
    self.when_pressed_function()
  File "/install/community-edition-setup/pylib/tui.py", line 725, in nextButtonPressed
    self.parentApp.installObject.check_properties()
  File "./setup.py", line 1007, in check_properties
    self.city = input('City: ').strip()
KeyboardInterrupt
```

[1] https://gluu.org/docs/gluu-server/4.2/installation-guide/setup_py/#setup-prompt

**Comment by mbaser** [comment]
Fixed
