### ISSUE TITLE
Installation fails due to missing java.properties

### ISSUE THREAD

**Issue by ehlo550** [GluuFederation/community-edition-setup#770]
Hi,

OS: Ubuntu 20.04.3 LTS

gluu-server-nochroot/focal-devel 4.3.0-6 amd64
gluu-server/focal-devel,now 4.3.1-121~ubuntu20.04 amd64 [installed]

When trying to install the as described [here](https://gluu.org/docs/gluu-server/4.3/installation-guide/install-ubuntu/) with a Local OpenDj backend, the installer crashes with the following error:

```
07:19:56 11/11/21 Configuring system
07:20:11 11/11/21 su: failed to execute /bin/bash: Permission denied

07:20:11 11/11/21 Error reading None
07:20:11 11/11/21 Traceback (most recent call last):
  File "/install/community-edition-setup/setup_app/utils/setup_utils.py", line 161, in readFile
    with open(inFilePath, rmode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/opendj/config/java.properties'

07:20:11 11/11/21 FATAL
07:20:11 11/11/21 Traceback (most recent call last):
  File "./setup.py", line 301, in do_installation
    openDjInstaller.start_installation()
  File "/install/community-edition-setup/setup_app/installers/base.py", line 37, in start_installation
    self.install()
  File "/install/community-edition-setup/setup_app/installers/opendj.py", line 47, in install
    self.install_opendj()
  File "/install/community-edition-setup/setup_app/installers/opendj.py", line 139, in install_opendj
    self.fix_opendj_java_properties()
  File "/install/community-edition-setup/setup_app/installers/opendj.py", line 347, in fix_opendj_java_properties
    opendj_java_properties = self.readFile(opendj_java_properties_fn).splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'
```

**Comment by ehlo550** [comment]
The install works when not using the TUI btw.
`/install/community-edition-setup/setup.py -c`

**Comment by mzico** [comment]
@MohitMaliFtechiz : can we do a quick QA please?

**Comment by MohitMaliFtechiz** [comment]
@mzico  ok let me test it

**Comment by MohitMaliFtechiz** [comment]
hi @mzico i just tried to install gluu-server-nochroot_4.3.0-6_amd64.deb.  it installed successfully with TUI
![Screenshot from 2021-11-12 18-02-14](https://user-images.githubusercontent.com/34593983/141467861-a09cd488-985f-4698-a734-e9d5cd90be1a.png)

**Comment by mbaser** [comment]
This is not issue, it happens when another process listens port 1636.
