### ISSUE TITLE
Missing oxAsimba configuration entry in LDAP

### ISSUE THREAD

**Issue by iromli** [GluuFederation/community-edition-setup#88]
I found that when Asimba sidebar menu is clicked, oxTrust raises the following error:
```
Feb 15, 2016 1:29:27 PM org.apache.catalina.core.ApplicationDispatcher invoke
SEVERE: Servlet.service() for servlet Faces Servlet threw exception
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to find entry: ou=oxasimba,ou=configuration,inum=@!0854.5657.36AD.3A95!0002!
0932.E1A1,ou=appliances,o=gluu
        at org.gluu.site.ldap.persistence.LdapEntryManager.find(LdapEntryManager.java:249)
        at org.gluu.site.ldap.persistence.AbstractEntryManager.find(AbstractEntryManager.java:427)
        at org.gluu.site.ldap.persistence.AbstractEntryManager.find(AbstractEntryManager.java:376)
        at org.gluu.oxtrust.ldap.service.AsimbaService.loadAsimbaConfiguration(AsimbaService.java:70)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
        at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56)
        at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
        at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
        at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
        at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107)
        at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196)                                     [84/1237]
        at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114)
```

Perhaps, we have missing oxAsimba configuration in LDAP.

**Comment by dmogn** [comment]
Fixed:
https://github.com/GluuFederation/community-edition-setup/blob/master/templates/configuration.ldif

**Comment by iromli** [comment]
@dmogn In Enterprise Edition, those new entries are rejected due to invalid schema. 

Here's log from rejected ldif file.
```
# Entry ou=selectors,ou=oxasimba,ou=configuration,inum=@!0854.5657.36AD.3A95!0002!0932.E1A1,ou=appliances,o=gluu read from LDIF starting at line 803 is
 not valid because it violates the server's schema configuration:  Entry ou=selectors,ou=oxasimba,ou=configuration,inum=@!0854.5657.36AD.3A95!0002!0932
.E1A1,ou=appliances,o=gluu violates the Directory Server schema configuration because it includes attribute oxRevision which is not allowed by any of t
he objectclasses defined in that entry
objectClass: top
objectClass: organizationalUnit
ou: selectors
oxRevision: 1

# Entry ou=requestors,ou=oxasimba,ou=configuration,inum=@!0854.5657.36AD.3A95!0002!0932.E1A1,ou=appliances,o=gluu read from LDIF starting at line 803 i
s not valid because it violates the server's schema configuration:  Entry ou=requestors,ou=oxasimba,ou=configuration,inum=@!0854.5657.36AD.3A95!0002!09
32.E1A1,ou=appliances,o=gluu violates the Directory Server schema configuration because it includes attribute oxRevision which is not allowed by any of
 the objectclasses defined in that entry
objectClass: top
objectClass: organizationalUnit
ou: requestors
oxRevision: 1

# Entry ou=requestorpools,ou=oxasimba,ou=configuration,inum=@!0854.5657.36AD.3A95!0002!0932.E1A1,ou=appliances,o=gluu read from LDIF starting at line 8
03 is not valid because it violates the server's schema configuration:  Entry ou=requestorpools,ou=oxasimba,ou=configuration,inum=@!0854.5657.36AD.3A95
!0002!0932.E1A1,ou=appliances,o=gluu violates the Directory Server schema configuration because it includes attribute oxRevision which is not allowed b
y any of the objectclasses defined in that entry
objectClass: top
objectClass: organizationalUnit
ou: requestorpools
oxRevision: 1

# Entry ou=oxasimba,ou=configuration,inum=@!0854.5657.36AD.3A95!0002!0932.E1A1,ou=appliances,o=gluu read from LDIF starting at line 803 is not valid be
cause it violates the server's schema configuration:  Entry ou=oxasimba,ou=configuration,inum=@!0854.5657.36AD.3A95!0002!0932.E1A1,ou=appliances,o=gluu
 violates the Directory Server schema configuration because it includes attribute oxRevision which is not allowed by any of the objectclasses defined i
n that entry
objectClass: top
objectClass: oxAsimbaConfiguration
ou: oxasimba
oxRevision: 1

# The parent entry 'ou=oxasimba,ou=configuration,inum=@!0854.5657.36AD.3A95!0002!0932.E1A1,ou=appliances,o=gluu' does not exist
ou=idps,ou=oxasimba,ou=configuration,inum=@!0854.5657.36AD.3A95!0002!0932.E1A1,ou=appliances,o=gluu
dn: ou=idps,ou=oxasimba,ou=configuration,inum=@!0854.5657.36AD.3A95!0002!0932.E1A1,ou=appliances,o=gluu
objectClass: organizationalUnit
objectClass: top
ou: idps
entryUUID: e7671a3c-3f18-35ae-b5d8-d5e916be96aa
```

If I comment out `oxRevision` in new entries, I no longer see the rejected error message. Perhaps, something is missing from `101-ox.ldif`? I'm not sure if we need `oxRevision` in oxAsimba configuration though.

**Comment by dmogn** [comment]
>> Perhaps, something is missing from 101-ox.ldif?
- Right. Fixed.

Also, Asimba defaut settings has been added to templates/configuration.ldif

**Comment by yurem** [comment]
Can you retest it in beta3?

**Comment by iromli** [comment]
> Can you retest it in beta3?

Sure, i will rebuild docker image with beta3 war files.

**Comment by iromli** [comment]
@dmogn Some entries are rejected. Here's the log from rejected file:

```
# Entry inum=@!2B96.42E9.2953.68ED!0002!D21C.8343!EEDB.B1D4.DFBF.3A38.21EE.2B81.2510.2CC8,ou=idps,ou=oxasimba,ou=configuration,inum=@!0854.5657.36AD.3A95!0002!0932.E1A1,ou=appliances,o=gluu read from LDIF starting at line 830 is not valid because it violates the server's schema configuration:  Entry inum=@!2B96.42E9.2953.68ED!0002!D21C.8343!EEDB.B1D4.DFBF.3A38.21EE.2B81.2510.2CC8,ou=idps,ou=oxasimba,ou=configuration,inum=@!0854.5657.36AD.3A95!0002!0932.E1A1,ou=appliances,o=gluu violates the Directory Server schema configuration because it includes attribute uniqueIdentifier which is not allowed by any of the objectclasses defined in that entry
objectClass: oxAsimbaIDP
# objectClass: top
friendlyname: Gluu Server CE
inum: @!2B96.42E9.2953.68ED!0002!D21C.8343!EEDB.B1D4.DFBF.3A38.21EE.2B81.2510.2CC8
oxasimbaentry: {"inum":"@!2B96.42E9.2953.68ED!0002!D21C.8343!EEDB.B1D4.DFBF.3A38.21EE.2B81.2510.2CC8","id":"https://ce.gluu.info/idp/shibboleth","sourceId":null,"friendlyName":"Gluu Server CE","metadataUrl":"https://ce.gluu.info/idp/shibboleth","metadataTimeout":-1,"metadataFile":"","enabled":true,"acsIndex":true,"scoping":false,"nameIdPolicy":false,"allowCreate":true,"nameIdFormat":null,"avoidSubjectConfirmations":false,"disableSSOForIDP":false,"lastModified":1455524023953}
uniqueIdentifier: https://ce.gluu.info/idp/shibboleth

# Entry inum=@!2B96.42E9.2953.68ED!0002!D21C.8343!1975.CC4F.ACC1.A803.A40D.AEC1.1C3A.285D,ou=requestorpools,ou=oxasimba,ou=configuration,inum=@!0854.5657.36AD.3A95!0002!0932.E1A1,ou=appliances,o=gluu read from LDIF starting at line 830 is not valid because it violates the server's schema configuration:  Entry inum=@!2B96.42E9.2953.68ED!0002!D21C.8343!1975.CC4F.ACC1.A803.A40D.AEC1.1C3A.285D,ou=requestorpools,ou=oxasimba,ou=configuration,inum=@!0854.5657.36AD.3A95!0002!0932.E1A1,ou=appliances,o=gluu violates the Directory Server schema configuration because it includes attribute uniqueIdentifier which is not allowed by any of the objectclasses defined in that entryEntry inum=@!2B96.42E9.2953.68ED!0002!D21C.8343!869E.85EC.BEC2.B1A6.0ECC.7902.5796.74A6,ou=requestors,ou=oxasimba,ou=configuration,inum=@!0854.5657.36AD.3A95!0002!0932.E1A1,ou=appliances,o=gluu read from LDIF starting at line 830 is not valid because it violates the server's schema configuration:  Entry inum=@!2B96.42E9.2953.68ED!0002!D21C.8343!869E.85EC.BEC2.B1A6.0ECC.7902.5796.74A6,ou=requestors,ou=oxasimba,ou=configuration,inum=@!0854.5657.36AD.3A95!0002!0932.E1A1,ou=appliances,o=gluu violates the Directory Server schema configuration because it includes attribute uniqueIdentifier which is not allowed by any of the objectclasses defined in that entry

objectClass: oxAsimbaSPRequestorobjectClass: oxAsimbaRequestorPool

objectClass: topobjectClass: top

friendlyname: Local Apache webserver Requestor
friendlyname: Requestor Pool 1
inum: @!2B96.42E9.2953.68ED!0002!D21C.8343!869E.85EC.BEC2.B1A6.0ECC.7902.5796.74A6
inum: @!2B96.42E9.2953.68ED!0002!D21C.8343!1975.CC4F.ACC1.A803.A40D.AEC1.1C3A.285D
oxasimbaentry: {"inum":"@!2B96.42E9.2953.68ED!0002!D21C.8343!869E.85EC.BEC2.B1A6.0ECC.7902.5796.74A6","id":"https://ce.gluu.info/shibboleth","friendlyName":"Apache webserver Requestor","metadataUrl":"https://ce.gluu.info/Shibboleth.sso/Metadata","metadataTimeout":-1,"metadataFile":"${webapp.root}/WEB-INF/sample-data/ce-localhost-sp.xml","poolID":"requestorpool.1","properties":null,"enabled":true,"signing":false,"lastModified":1455524077539}
oxasimbaentry: {"inum":"@!2B96.42E9.2953.68ED!0002!D21C.8343!1975.CC4F.ACC1.A803.A40D.AEC1.1C3A.285D","id":"requestorpool.1","friendlyName":"Requestor Pool 1","enabled":true,"lastModified":1455524056416,"forcedAuthenticate":false,"preAuthorizationProfileID":null,"postAuthorizationProfileID":"postauthz.1","attributeReleasePolicyID":"asimba.releasepolicy.1","properties":null,"authenticationProfileIDs":"remote.saml2","requestors":null}
uniqueIdentifier: https://ce.gluu.info/shibboleth
uniqueIdentifier: requestorpool.1


# # Entry inum=@!2B96.42E9.2953.68ED!0002!D21C.8343!3627.987E.69FE.6A8B.C478.2586.E944.04C0,ou=selectors,ou=oxasimba,ou=configuration,inum=@!0854.5657.36AD.3A95!0002!0932.E1A1,ou=appliances,o=gluu read from LDIF starting at line 830 is not valid because it violates the server's schema configuration:  Entry inum=@!2B96.42E9.2953.68ED!0002!D21C.8343!3627.987E.69FE.6A8B.C478.2586.E944.04C0,ou=selectors,ou=oxasimba,ou=configuration,inum=@!0854.5657.36AD.3A95!0002!0932.E1A1,ou=appliances,o=gluu violates the Directory Server schema configuration because it includes attribute uniqueIdentifier which is not allowed by any of the objectclasses defined in that entryEntry inum=@!2B96.42E9.2953.68ED!0002!D21C.8343!869E.85EC.BEC2.B1A6.0ECC.4987.7891.5325,ou=requestors,ou=oxasimba,ou=configuration,inum=@!0854.5657.36AD.3A95!0002!0932.E1A1,ou=appliances,o=gluu read from LDIF starting at line 830 is not valid because it violates the server's schema configuration:  Entry inum=@!2B96.42E9.2953.68ED!0002!D21C.8343!869E.85EC.BEC2.B1A6.0ECC.4987.7891.5325,ou=requestors,ou=oxasimba,ou=configuration,inum=@!0854.5657.36AD.3A95!0002!0932.E1A1,ou=appliances,o=gluu violates the Directory Server schema configuration because it includes attribute uniqueIdentifier which is not allowed by any of the objectclasses defined in that entry

objectClass: oxAsimbaSPRequestor
objectClass: oxAsimbaSelector
objectClass: top
objectClass: top
friendlyname: Gluu Test SP
friendlyname: Selector rule 1, shibboleth SP -> shibboleth IDP
inum: @!2B96.42E9.2953.68ED!0002!D21C.8343!869E.85EC.BEC2.B1A6.0ECC.4987.7891.5325
inum: @!2B96.42E9.2953.68ED!0002!D21C.8343!3627.987E.69FE.6A8B.C478.2586.E944.04C0
oxasimbaentry: {"inum":"@!2B96.42E9.2953.68ED!0002!D21C.8343!869E.85EC.BEC2.B1A6.0ECC.4987.7891.5325","id":"http://sptest2.gluu.org/secure","friendlyName":"Gluu Test SP","metadataUrl":null,"metadataTimeout":-1,"metadataFile":"${webapp.root}/WEB-INF/sample-data/sptest2.xml","poolID":"requestorpool.1","properties":null,"enabled":true,"signing":false,"lastModified":1455524077539}organizationid: https://ce.gluu.info/idp/shibboleth

uniqueIdentifier: http://sptest2.gluu.org/secure

oxasimbaentry: {"inum":"@!2B96.42E9.2953.68ED!0002!D21C.8343!3627.987E.69FE.6A8B.C478.2586.E944.04C0","id":"https://ce.gluu.info/shibboleth","organizationId":"https://ce.gluu.info/idp/shibboleth","friendlyName":"Selector rule 1, shibboleth SP -> shibboleth IDP","enabled":true,"lastModified":1455524102424}
uniqueIdentifier: https://ce.gluu.info/shibboleth
```

Note, i'm using `101-ox.ldif` schema as seen in this [template](https://github.com/GluuFederation/community-edition-setup/blob/6fa384f38bdb6ba0463105e80d06dd5714767559/static/opendj/101-ox.ldif)

**Comment by dmogn** [comment]
>> violates the Directory Server schema configuration because it includes attribute uniqueIdentifier which is not allowed by any of the objectclasses defined in that entry

- Hm... uniqueIdentifier is part of exiting oxTrust classes. But latest 101.ldif does not define uniqueIdentifier attribute.

**Comment by dmogn** [comment]
Fixed. The fix has been tested on BETA-3.

**Comment by iromli** [comment]
The entry seems good, however I found this error when clicked the Asimba menu in left sidebar:

```
2016-02-28 01:01:26,565 ERROR [org.jboss.seam.exception.Exceptions] handled and logged exception
javax.servlet.ServletException: /asimba/idps.xhtml @76,92 value="#{idp.identificationURL}": Property 'identificationURL' not found on type org.gluu.asi
mba.util.ldap.idp.IDPEntry
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:606)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
        at org.jboss.seam.web.RewriteFilter.process(RewriteFilter.java:98)
        at org.jboss.seam.web.RewriteFilter.doFilter(RewriteFilter.java:57)
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
        at org.jboss.seam.web.LoggingFilter.doFilter(LoggingFilter.java:60)
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
        at org.jboss.seam.web.IdentityFilter.doFilter(IdentityFilter.java:40)
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73)
        at org.jboss.seam.web.ExceptionFilter.doFilter(ExceptionFilter.java:64)
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
        at org.jboss.seam.web.RedirectFilter.doFilter(RedirectFilter.java:45)
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73)
        at org.jboss.seam.servlet.SeamFilter.doFilter(SeamFilter.java:158)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)                                    [13/58]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.el.PropertyNotFoundException: /asimba/idps.xhtml @76,92 value="#{idp.identificationURL}": Property 'identificationURL' not found on ty
pe org.gluu.asimba.util.ldap.idp.IDPEntry
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:111)
        at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:186)
        at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:174)
        at javax.faces.component.UIOutput.getValue(UIOutput.java:169)
        at com.sun.faces.renderkit.html_basic.HtmlBasicInputRenderer.getValue(HtmlBasicInputRenderer.java:205)
        at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.getCurrentValue(HtmlBasicRenderer.java:355)
        at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeEnd(HtmlBasicRenderer.java:164)
        at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:875)
        at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:312)
        at com.sun.faces.renderkit.html_basic.TableRenderer.renderRow(TableRenderer.java:384)
        at com.sun.faces.renderkit.html_basic.TableRenderer.encodeChildren(TableRenderer.java:161)
        at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:845)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1779)
        at javax.faces.render.Renderer.encodeChildren(Renderer.java:168)
        at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:845)
        at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304)
        at com.sun.faces.renderkit.html_basic.GridRenderer.renderRow(GridRenderer.java:185)
        at com.sun.faces.renderkit.html_basic.GridRenderer.encodeChildren(GridRenderer.java:129)
        at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:845)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1779)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1782)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1782)
        at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:402)
        at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:125)
        at org.jboss.seam.jsf.SeamViewHandler.renderView(SeamViewHandler.java:188)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:286)
        at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:121)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
        at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:139)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:594)
        ... 39 more
```

Previously, I didn't see the error above and able to see a search form field.

**Comment by iromli** [comment]
Fixed in oxTrust build date 2016-02-29.
