### ISSUE TITLE
Post install SCIM throwing error

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#926]
Error showing this: 

```
-bash-4.2# ./post-setup-add-components.py -addscim
Current Gluu Version 4.2.3
Downloading Community Edition Setup 4.2.3
2022-09-28 05:35:53 URL:https://codeload.github.com/GluuFederation/community-edition-setup/zip/refs/heads/version_4.2.3 [654534] -> "/install/community-edition-setup-version_4.2.3/version_4.2.3.zip" [1]
Extracting package
Detected OS red 7
Detected OS red 7
Traceback (most recent call last):
  File "./post-setup-add-components.py", line 107, in <module>
    setupObj.initialize()
  File "/install/community-edition-setup-version_4.2.3/setup.py", line 882, in initialize
    oxauth_client_jar_zf = zipfile.ZipFile(self.non_setup_properties['oxauth_client_jar_fn'])
  File "/usr/lib64/python3.6/zipfile.py", line 1108, in __init__
    self._RealGetContents()
  File "/usr/lib64/python3.6/zipfile.py", line 1175, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

Hao thankfully supplied patch: 

```
Modify /install/community-edition-setup-version_4.2.3/setup.py around line 879:

           #self.run(['wget', '-nv', oxauth_client_jar_url, '-O', self.non_setup_properties['oxauth_client_jar_fn']])

            os.system('wget -nv --no-check-certificate {} -O {}'.format(oxauth_client_jar_url, self.non_setup_properties['oxauth_client_jar_fn']))
```

Please merge this patch.

**Comment by devrimyatar** [comment]
@mzico 
File  `oxauth-client-jar-without-provider-dependencies.jar` is supposed to be exist on right location. He deleted that file, and found a way to re-download. Thus, this change is not required.
