### ISSUE TITLE
CentOS 7.1 setup.py error

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/community-edition-setup#96]
The new package was installed with shibIdp, Asimba and CAS. The following error was found in the `setup_error.log` file. httpd and tomcat showed `inactive (dead)`.  Error for starting tomcat:

```
[root@gluu-server-2 ~]# service tomcat start
Redirecting to /bin/systemctl start  tomcat.service
Failed to start tomcat.service: Unit tomcat.service failed to load: No such file or directory.
```
Error in setup_error.log
```
19:51:27 03/02/16 Error running command : /usr/java/latest/bin/keytool -importkeystore -srckeystore /etc/certs/shibIDP.pkcs12 -srcstorepass MjikM8Warb92 -srcstoretype PKCS12 -destkeystore /etc/certs/shibIDP.jks -deststorepass MjikM8Warb92 -deststoretype JKS -keyalg RSA -noprompt
19:51:27 03/02/16 Traceback (most recent call last):
  File "./setup.py", line 1495, in run
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

19:51:27 03/02/16 /bin/chown: cannot access ‘/etc/certs/shibIDP.jks’: No such file or directory

19:51:27 03/02/16 /bin/chmod: cannot access ‘/etc/certs/shibIDP.jks’: No such file or directory

19:51:27 03/02/16 Error running command : /usr/java/latest/bin/keytool -importkeystore -srckeystore /etc/certs/asimba.pkcs12 -srcstorepass 5ExzRYOjyeRq -srcstoretype PKCS12 -destkeystore /etc/certs/asimbaIDP.jks -deststorepass 5ExzRYOjyeRq -deststoretype JKS -keyalg RSA -noprompt
19:51:27 03/02/16 Traceback (most recent call last):
  File "./setup.py", line 1495, in run
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

19:51:27 03/02/16 /bin/chown: cannot access ‘/etc/certs/asimbaIDP.jks’: No such file or directory

19:51:27 03/02/16 /bin/chmod: cannot access ‘/etc/certs/asimbaIDP.jks’: No such file or directory

19:51:27 03/02/16 bash: /usr/java/latest/bin/java: No such file or directory

19:51:27 03/02/16 Error loading file
19:51:27 03/02/16 Traceback (most recent call last):
  File "./setup.py", line 1463, in generate_base64_file
    plain_file = open(fn)
IOError: [Errno 2] No such file or directory: '/etc/certs/oxauth-web-keys.json'

19:51:27 03/02/16 ***** Error caught in main loop *****
19:51:27 03/02/16 Traceback (most recent call last):
  File "./setup.py", line 1817, in <module>
    installObject.generate_base64_configuration()
  File "./setup.py", line 1483, in generate_base64_configuration
    self.oxauth_openid_key_base64 = self.generate_base64_ldap_file(self.oxauth_openid_key_json)
  File "./setup.py", line 1477, in generate_base64_ldap_file
    return self.generate_base64_file(fn, 1)
  File "./setup.py", line 1472, in generate_base64_file
    plain_file_b64encoded_text = self.reindent(plain_file_b64encoded_text, num_spaces)
  File "./setup.py", line 1453, in reindent
    text = string.split(text, '\n')
  File "/usr/lib64/python2.7/string.py", line 292, in split
    return s.split(sep, maxsplit)
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by aveekbu** [comment]
@zamilskhan I've encountered the same error on CentOS 7.2 as well.

**Comment by zamilskhan** [comment]
New error in 7.1 It does not start now

```
[root@centos7 ~]# /sbin/gluu-serverd-2.4.2 start
Job for systemd-nspawn@gluu_server_2.4.2.service failed. See 'systemctl status systemd-nspawn@gluu_server_2.4.2.service' and 'journalctl -xn' for details.
[root@centos7 ~]# systemctl status systemd-nspawn@gluu_server_2.4.2.service
systemd-nspawn@gluu_server_2.4.2.service - Container gluu_server_2.4.2
   Loaded: loaded (/usr/lib/systemd/system/systemd-nspawn@gluu_server_2.4.2.service; disabled)
   Active: failed (Result: exit-code) since Fri 2016-03-04 20:00:31 GMT; 9s ago
     Docs: man:systemd-nspawn(1)
  Process: 4045 ExecStart=/usr/bin/systemd-nspawn --quiet --boot --link-journal=try-guest --machine=%I (code=exited, status=1/FAILURE)
 Main PID: 4045 (code=exited, status=1/FAILURE)

Mar 04 20:00:31 centos7.gluu.info systemd[1]: systemd-nspawn@gluu_server_2.4.2.service: main process exited, code=exited, status=1/FAILURE
Mar 04 20:00:31 centos7.gluu.info systemd[1]: Failed to start Container gluu_server_2.4.2.
Mar 04 20:00:31 centos7.gluu.info systemd[1]: Unit systemd-nspawn@gluu_server_2.4.2.service entered failed state.
Mar 04 20:00:31 centos7.gluu.info systemd-nspawn[4045]: /usr/bin/systemd-nspawn: unrecognized option '--quiet'
```

**Comment by adrian-gluu** [comment]
can you test this only on centos 7.2:
http://repo.gluu.org/centos/7/gluu-server-2.4.2-1-1.centos7.x86_64.rpm

**Comment by mzico** [comment]
@adrian-gluu : it doesn't work. [https://github.com/GluuFederation/community-edition-setup/issues/92](Here) is the link.

**Comment by adrian-purism** [comment]
can you test this one?
http://repo.gluu.org/centos/7/gluu-server-2.4.2-1-2.centos7.x86_64.rpm

**Comment by zamilskhan** [comment]
It is resolved,
