### ISSUE TITLE
RHEL 6.x setup.py error

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/community-edition-setup#97]
The `setup_error.log` is given below; only the errors are given

```
16:53:25 03/02/16 Certificate was added to keystore

16:53:25 03/02/16 Entry for alias idp.gluu.info successfully imported.
Import command completed:  1 entries successfully imported, 0 entries failed or cancelled

16:53:26 03/02/16 Entry for alias idp.gluu.info successfully imported.
Import command completed:  1 entries successfully imported, 0 entries failed or cancelled

16:53:45 03/02/16 Unable to initialize log
java.io.IOException: Permission denied
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2001)
	at java.io.File.createTempFile(File.java:2047)
	at org.opends.quicksetup.installer.SetupLauncher.main(SetupLauncher.java:68)
Unable to initialize log
java.io.IOException: Permission denied
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2001)
	at java.io.File.createTempFile(File.java:2047)
	at org.opends.server.tools.InstallDS.mainCLI(InstallDS.java:331)
	at org.opends.server.tools.InstallDS.mainCLI(InstallDS.java:286)
	at org.opends.quicksetup.installer.SetupLauncher.launch(SetupLauncher.java:138)
	at org.opends.quicksetup.installer.SetupLauncher.main(SetupLauncher.java:75)
Mar 02, 2016 4:53:30 PM org.opends.quicksetup.CurrentInstallStatus getPort
INFO: Failed to get port
java.io.FileNotFoundException: /opt/opendj/./config/config.ldif (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at java.io.FileReader.<init>(FileReader.java:72)
	at org.opends.quicksetup.Configuration.load(Configuration.java:331)
	at org.opends.quicksetup.Configuration.getLowerCaseContents(Configuration.java:298)
	at org.opends.quicksetup.Configuration.getLDAPPort(Configuration.java:191)
	at org.opends.quicksetup.Configuration.getPort(Configuration.java:92)
	at org.opends.quicksetup.CurrentInstallStatus.getPort(CurrentInstallStatus.java:178)
	at org.opends.quicksetup.CurrentInstallStatus.<init>(CurrentInstallStatus.java:80)
	at org.opends.server.tools.InstallDS.checkInstallStatus(InstallDS.java:622)
	at org.opends.server.tools.InstallDS.execute(InstallDS.java:417)
	at org.opends.server.tools.InstallDS.mainCLI(InstallDS.java:341)
	at org.opends.server.tools.InstallDS.mainCLI(InstallDS.java:286)
	at org.opends.quicksetup.installer.SetupLauncher.launch(SetupLauncher.java:138)
	at org.opends.quicksetup.installer.SetupLauncher.main(SetupLauncher.java:75)

Failed to initialize log
```
Copying files to opendj was ok.
```
16:55:54 03/02/16 Certificate was added to keystore

16:55:54 03/02/16 Error running command : /usr/bin/jar xf /opt/tomcat/webapps/identity.war WEB-INF/lib/oxtrust-configuration-2.4.2.Final.jar
16:55:54 03/02/16 Traceback (most recent call last):
  File "./setup.py", line 1495, in run
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1238, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

16:55:54 03/02/16 Error running command : /usr/bin/jar xf WEB-INF/lib/oxtrust-configuration-2.4.2.Final.jar
16:55:54 03/02/16 Traceback (most recent call last):
  File "./setup.py", line 1495, in run
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1238, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

16:55:54 03/02/16 Error copying tree /opt/dist/tmp_identity/shibboleth2 to /opt/tomcat/conf/shibboleth2
16:55:54 03/02/16 Traceback (most recent call last):
  File "./setup.py", line 515, in copyTree
    for item in os.listdir(src):
OSError: [Errno 2] No such file or directory: '/opt/dist/tmp_identity/shibboleth2'

16:55:54 03/02/16 Error copying ./static/tomcat/attribute-resolver.xml.vm to /opt/tomcat/conf/shibboleth2/idp/
16:55:54 03/02/16 Traceback (most recent call last):
  File "./setup.py", line 504, in copyFile
    shutil.copy(inFile, destFolder)
  File "/usr/lib64/python2.6/shutil.py", line 84, in copy
    copyfile(src, dst)
  File "/usr/lib64/python2.6/shutil.py", line 51, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 21] Is a directory: '/opt/tomcat/conf/shibboleth2/idp/'

16:55:54 03/02/16 Error running command : /usr/bin/jar xf /opt/dist/oxcas.war
16:55:54 03/02/16 Traceback (most recent call last):
  File "./setup.py", line 1495, in run
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1238, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

16:55:54 03/02/16 Error copying ./output/cas.properties to /opt/dist/tmp_cas/WEB-INF/cas.properties
16:55:54 03/02/16 Traceback (most recent call last):
  File "./setup.py", line 504, in copyFile
    shutil.copy(inFile, destFolder)
  File "/usr/lib64/python2.6/shutil.py", line 84, in copy
    copyfile(src, dst)
  File "/usr/lib64/python2.6/shutil.py", line 51, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/opt/dist/tmp_cas/WEB-INF/cas.properties'

16:55:54 03/02/16 Error running command : /usr/bin/jar cmf tmp_cas/META-INF/MANIFEST.MF cas.war -C /opt/dist/tmp_cas/ .
16:55:54 03/02/16 Traceback (most recent call last):
  File "./setup.py", line 1495, in run
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1238, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

16:55:54 03/02/16 Error copying /opt/dist/cas.war to /opt/tomcat/webapps
16:55:54 03/02/16 Traceback (most recent call last):
  File "./setup.py", line 504, in copyFile
    shutil.copy(inFile, destFolder)
  File "/usr/lib64/python2.6/shutil.py", line 84, in copy
    copyfile(src, dst)
  File "/usr/lib64/python2.6/shutil.py", line 50, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/opt/dist/cas.war'

16:56:43 03/02/16 --2016-03-02 16:55:54--  http://ox.gluu.org/maven/org/asimba/asimba-wa/2.4.2.Final/asimba-wa-2.4.2.Final.war
Resolving ox.gluu.org... 162.243.99.240
Connecting to ox.gluu.org|162.243.99.240|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 29876775 (28M) [application/x-troff-man]
Saving to: `/opt/dist/oxasimba.war'
```
```
2016-03-02 16:56:43 (613 KB/s) - `/opt/dist/oxasimba.war' saved [29876775/29876775]


16:56:43 03/02/16 Error running command : /usr/bin/jar xf /opt/dist/oxasimba.war
16:56:43 03/02/16 Traceback (most recent call last):
  File "./setup.py", line 1495, in run
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1238, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

16:56:43 03/02/16 Error copying ./output/asimba.xml to /opt/dist/tmp_asimba/WEB-INF/conf/asimba.xml
16:56:43 03/02/16 Traceback (most recent call last):
  File "./setup.py", line 504, in copyFile
    shutil.copy(inFile, destFolder)
  File "/usr/lib64/python2.6/shutil.py", line 84, in copy
    copyfile(src, dst)
  File "/usr/lib64/python2.6/shutil.py", line 51, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/opt/dist/tmp_asimba/WEB-INF/conf/asimba.xml'

16:56:43 03/02/16 Error copying ./output/asimba.properties to /opt/dist/tmp_asimba/WEB-INF/asimba.properties
16:56:43 03/02/16 Traceback (most recent call last):
  File "./setup.py", line 504, in copyFile
    shutil.copy(inFile, destFolder)
  File "/usr/lib64/python2.6/shutil.py", line 84, in copy
    copyfile(src, dst)
  File "/usr/lib64/python2.6/shutil.py", line 51, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/opt/dist/tmp_asimba/WEB-INF/asimba.properties'

16:56:43 03/02/16 Error running command : /usr/bin/jar cmf tmp_asimba/META-INF/MANIFEST.MF asimba.war -C /opt/dist/tmp_asimba/ .
16:56:43 03/02/16 Traceback (most recent call last):
  File "./setup.py", line 1495, in run
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1238, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

16:56:43 03/02/16 Error copying /opt/dist/asimba.war to /opt/tomcat/webapps
16:56:43 03/02/16 Traceback (most recent call last):
  File "./setup.py", line 504, in copyFile
    shutil.copy(inFile, destFolder)
  File "/usr/lib64/python2.6/shutil.py", line 84, in copy
    copyfile(src, dst)
  File "/usr/lib64/python2.6/shutil.py", line 50, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/opt/dist/asimba.war'
```

**Comment by yurem** [comment]
I have suspicious that opendj in rhel6 isn't clean. Andrian can you check if we didn't run it installation already?

Regarding other errors... All of them are not clear because according to them wget can download file into /opt/dists but jar can't extract it.I have idea. There is no /usr/bin/jar command in rhel. In this case we need to find where it in rhel and update setup to cover this case too.

**Comment by adrian-gluu** [comment]
the hole /opt folder is the same in all of them, ubuntu centos and rhel, in rhel we didnt run any installation

**Comment by yurem** [comment]
>> There is no /usr/bin/jar command in rhel. In this case we need to find where it in rhel and update setup to cover this case too.
@adrian-gluu , @zamilskhan can you check this?

**Comment by zamilskhan** [comment]
@yurem there is no `/usr/bin/jar` in RHEL 6.7 and I could not find any jar using the find command.

**Comment by yurem** [comment]
@adrian-gluu If there is no OenJDK 1.7.x in RHEL we need to install it
@nynymike

**Comment by adrian-gluu** [comment]
http://repo.gluu.org/rhel/7/gluu-server-2.4.2-1-1.rhel7.x86_64.rpm
http://repo.gluu.org/rhel/testing/gluu-server-2.4.2-1-1.rhel6.x86_64.rpm

**Comment by yurem** [comment]
Which OpenjDK version we uses in RHEL ?

**Comment by adrian-purism** [comment]
1.7.x

**Comment by nynymike** [comment]
Aveek, can you check to see if this issue is resolved?

**Comment by adrian-gluu** [comment]
http://repo.gluu.org/rhel/testing/gluu-server-2.4.2-1-1.rhel6.x86_64.rpm

**Comment by aveekbu** [comment]
RHEL6.x arch x.86_64 is now working fine. 
The Issue is resolved!
